### ISSUE TITLE
Multiple pisa biounits with same size: choice is random, is there a better strategy?

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#10]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Wednesday Aug 13, 2014 at 10:59 GMT_
_Originally opened as https://github.com/eppic-team/eppic-cli/issues/15_

---

When multiple PISA biounits are annotated in the PDB/mmCIF file and all are of the same macromolecular size we choose one at random (since we decided not to have multiplicity of biounits in the database). Is there a better strategy than choosing one at random? 

This affects the case 3gzh: it has 2 tetrameric assemblies predicted by PISA:
- assembly 1 (size 4): interfaces 1,2,3
- assembly 2 (size 4): interfaces 2,4,9

In `DataModelAdaptor` we sort the assemblies by sizes and choose the last one, which would correspond to the largest, except if all are same size when the last one is whoever comes last (by chance or rather by choice of the sorting algorithm)

**Comment by sbliven** [comment]
I think we should have all biounits in the db. This is important for integration with other tools, e.g. PDBe.

**Comment by josemduarte** [comment]
See also https://github.com/eppic-team/eppic-science/issues/91

**Comment by josemduarte** [comment]
This issue referred to eppic 2.1. Things are a bit different in eppic 3. I'll create a new issue that has the parts that apply to 3 and close this one.
