### ISSUE TITLE
Displaying PDB BU assignments

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#100]
We've got the matching between PDB's BU assignments and our list of valid assemblies, we could easily mark the PDB BU assignments in some special way in the WUI. That way it would be very easy to compare our predictions to the PDB annotations.

I'll assign this to 3.0, but if time is pressing, it can go to 3.1

[Issue split from #54]

**Comment by josemduarte** [comment]
One complication is that some PDB assignments are non-valid topologically, which means that this issue depends on #102. 

I'll move this to 3.1 for the moment...

**Comment by lafita** [comment]
At the moment, the **PDB1** BU Annotations are stored in the **AssemblyScore** table, with score equal to -1 and the call **XTAL**, if the assembly is not the pdb1, or **BIO**, if the assembly is the pdb1. This is very memory inefficient and difficult to handle, in case we want to mark the **PDB1** assemblies in the wui or query the database. 

I propose to introduce an indicator (boolean, bit(1) field) in the **Assembly** table, where 1 indicates that the assembly is the pdb1 and 0 indicates that the assembly is not the pdb1.

**Comment by josemduarte** [comment]
The current system is indeed a bit redundant. At the same time the advantage is that the current system allows for any arbitrary number of assembly prediction/annotation methods to be stored in the AssemblyScore table, e.g. we can have pdb2, pdb3, etc. (which is something we might want to do, see https://github.com/eppic-team/eppic-science/issues/91)

**Comment by josemduarte** [comment]
I've implemented a basic displaying of the pdb1 biounit assignment by simply showing an icon next to the prediction (the icon is definitely open for improvement). It's in branch issue100, now deployed on dev server.

**Comment by josemduarte** [comment]
I've merged the issue100 branch now.

**Comment by josemduarte** [comment]
I'll close, please open if someone feels like improving the current basic implementation.
