### ISSUE TITLE
PDB_DIR check fails

### ISSUE THREAD

**Issue by lafita** [eppic-team/eppic#108]
I get this Error:
<pre>
12:07:26 [main] ERROR eppic.Main - To be able to use PDB codes as input with -i option, 
a valid ATOM_CACHE_PATH must be set in config file, or through environment variable 
PDB_DIR. It must contain the PDB mmCIF gzip file repository in same divided layout as 
PDB ftp.
</pre>

I am running eppic main with the arguments:
<pre>
Main -i 2hda -o /afs/psi.ch/user/l/lafita_a/diagram/2hda
</pre>
and the JVM arguments:
<pre>
Xmx8G -Xms2G -DPDB_DIR=/scratch/cache/ -DPDB_CACHE=/scratch/cache/
</pre>
so my PDB_DIR is set as an environment variable.

Removing the eppic check for the PDB_DIR (see commit 08a366ab62867a8c3d3df623a435a877bd1a3580 in my diagrams branch) solves the issue.

Is that check needed, or should **eppic** rely entirely on **BioJava** when accessing structure files. In case the check is not needed I could merge the commit that removes it to the master branch.

**Comment by lafita** [comment]
If we maintain the check, why is the **PDB_DIR** variable obtained using `Map<String,String> env = System.getenv();` instead of using `System.getProperties()`?

**Comment by josemduarte** [comment]
One important distinction here: system properties and environmental variables are 2 totally different things:

- System properties: passed with `-D` to the JVM and accessed in java via `System.getProperties()`
- Environment variables: set at the OS level (with export in linux bash) and accessed in java via `System.getenv()`

In eppic I decided to use 2 ways of setting PDB_DIR: through the config file and through the environmental variable. We could also support setting it through the system property, in that case we'd need to add that check to in `EppicParams.checkCommandLineInput()`

**Comment by sbliven** [comment]
Nice patch, @lafita. 

One thing to note would be that if the check were removed altogether then everything would still function perfectly, with structures being downloaded to /tmp. Having a check at all only really makes sense for high-throughput usecases where you'd prefer the job to fail rather than download the PDB due to a poor configuration file.

**Comment by josemduarte** [comment]
That's right, perhaps we should simply make it a warning.
