### ISSUE TITLE
Link to show full Unit Cell

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#111]
On the structure page (#id), add a link to the general info panel for the full latticeGraph. Link should be similar in form and style to 'View Unit Cell' on the assembly page, but should pass the parameter `interfaces=*`

**Comment by josemduarte** [comment]
Also the current "View unit cell" link in the topology panel should link to `interfaces=*`, at the moment the link points to show interface members of current assembly only.

**Comment by sbliven** [comment]
@josemduarte The topology panel is currently only shown on the assembly page, so it makes sense for the link to specify the interfaces. We just need a link on the other pages to show the full cell with all interfaces.

**Comment by josemduarte** [comment]
I agree to that in principle. But in the topology panel there's 2 links at the moment: 

1. a link on the graph icon: I'd say this link should open the specific assembly's interfaces 
2. a link with text "View Unit Cell": shouldn't this link open the full cell with all interfaces? Or what's its purpose?

**Comment by gcapitani** [comment]
The graph icon link is actually meant to open the 2D lattice graph representation and not the 3D one
as it does now, so this needs to be changed.
To make things clearer, one solution is to modify the text link in individual assembly pages to "View unit cell for this assembly" and to put a new text link with "View unit cell" in the General Information panel of the structure page, passing the parameter interfaces=*.
We can try this and see if it looks clear and practical.

**Comment by gcapitani** [comment]
The text link with "View unit cell" in the General Information panel of the structure page is now implemented.

**Comment by sbliven** [comment]
The 'Show Assembly in Unit Cell' link is broken again. It should go to the LatticeGraphServlet, not the AssemblyDiagramServelet.

It looks like in `TopologyInfoPanel`, both the assembly diagram and the unit cell link are both using DiagramViewerRunner.runViewerAssembly.
