### ISSUE TITLE
Can't edit URL in popup boxes

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#112]
When creating the popup window for the latticeGraph, we're currently preventing the URL from being edited. This is very annoying if you want to change the interfaces manually. We should rethink whether we really want this as the restricted pop-up style, or maybe it could just be a normal tab.

**Comment by sbliven** [comment]
Hmm, may be a chrome-specific thing: http://stackoverflow.com/questions/2572333/google-chrome-window-open-workaround

Also, I have this behavior can be [disabled in Firefox](http://kb.mozillazine.org/Prevent_websites_from_disabling_new_window_features) by individual users, but I haven't found the Chrome equivalent.

Calling window.open() seems to be [not recommended](http://www.gtalbot.org/BugzillaSection/Bug195867GDR_WindowOpen.html#UsabilityIssues) in general, although the reasons for that might not apply for GWT.

**Comment by josemduarte** [comment]
I'd be happy with a normal tab with editable url. The other day I faced exactly the same problem and was annoyed by not being able to edit.

**Comment by gcapitani** [comment]
Both seem good solutions, we are now going for editable URL in the popup window, let's see if it works OK, if not we will try the normal tab.

**Comment by gcapitani** [comment]
The 3D lattice graph representation for assemblies (link View Assembly in Unit Cell) now open is a normal tab, so the URL is editable. We have the same behavior also for the 3D view of individual assemblies in the Assemblies page.

**Comment by gcapitani** [comment]
Seems to work fine, closing this issue.
