### ISSUE TITLE
Formatting of stoichiometry strings with subscripts

### ISSUE THREAD

**Issue by gcapitani** [eppic-team/eppic#113]
Stoichiometry strings are currently being shown with uniform case, e.g. A2, ABC etc. 
This is OK in most cases but can be confusing for entries with chains named with numbers: for instance, entry 4rft, which has 60 copies of chain 0, exhibits for the various assemblies stoichiometries like 03, 05, 060. This can be confusing for the user, a straightforward solution is to use subscripts for chain multiplicity, so for instance 0<sub>60</sub> instead of 060.

**Comment by gcapitani** [comment]
An alternative format is the one with parenthesis: 0(60)

**Comment by sbliven** [comment]
We also need to add a space or comma between chains, at least if we want to continue dropping the number for single copies. For instance, "AB" would generally refer to "A"<sub>1</sub>"B"<sub>1</sub>, but it could also refer to a single copy of the two-letter chain "AB"<sub>1</sub>. It's better to write "A B" or "A,B".

**Comment by gcapitani** [comment]
"A,B" in the current notation actually indicates two independent entities ("cocrystal")

**Comment by sbliven** [comment]
I've implemented a parenthesis format for text-based output. Maybe @altheaparker can take a look at how to include the subscript format in the WUI.

**Comment by josemduarte** [comment]
@sbliven good point about the 2-letter chain ids 

The parenthesis format for text based things looks good to me, +1 to that. 

The subscripts should be good for the wui too, let's see how they look once we have them.

One important thing: I've created 3 different stoichiometry strings in database (not yet on dev server but on git):
- stoichiometry: based on sequential letters A, ..., A, AA, ..., AZ, BA, ....., ZZ
- composition: based on chain ids
- compositionRepChainIds: based on representative chain ids (i.e. first chain id of entity)

Whatever solution we implement we need to remember to do the same for all those strings.

**Comment by gcapitani** [comment]
Works OK now (see test entry 3hbx)

**Comment by josemduarte** [comment]
Looks good!

This depends on stoichiometry strings being written to db with parenthesis, doesn't it? Do we have that in master already?

**Comment by sbliven** [comment]
@josemduarte I refactored `Stoichiometry` fairly extensively recently, which is now in master. I did include the parentheses in that commit, but I didn't test extensively to make sure that that was the only place it needed to be fixed.

For testing @altheaparker's commit, we just manually modified an entry (3hbx) to have the expected format. We definitely need to recompute a dev database soon.
