### ISSUE TITLE
NCS operators are not used

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#114]
This is a long standing issue: NCS operators specified in `struct_ncs_oper` in mmCIF (in MTRXn records in pdb) are not taken into account while reconstructing the crystal, thus the crystal is incomplete resulting in very few interfaces and assemblies calculated wrongly.

This is present often in viral capsid proteins e.g. 1auy. Also in some normal structures were for some legacy reasons the operators were added instead of having the chain explicitly as another normal NCS chain e.g. 1a37.

**Comment by josemduarte** [comment]
A method to do the expansion of the NCS chains is now implemented in biojava (see https://github.com/biojava/biojava/commit/adb09876561e264f28a3ba0ff9f3230c51d7933a) and should go out in 5.0. I've tried it with eppic and all works. 

While eppic stays based in biojava 4.2.x the feature will be unavailable. If we move eppic to biojava 5 eventually, then we'll be able to use that code too. In the meantime I can add the code to the eppic repo too so that we can use it.

**Comment by josemduarte** [comment]
Now fixed by adding a `StructureUtils` class, needs more testing. Eventually we need to repoint the code to biojava. I'll keep this open.

**Comment by sbliven** [comment]
https://github.com/eppic-team/eppic-science/issues/107 is a cool test case for this.

**Comment by josemduarte** [comment]
This is done. Just needs some testing. Will add a tag for that.

**Comment by sbliven** [comment]
So I guess we need to add `StructureUtils.expandNcsOps(struc)` to every main method that loads a structure?

**Comment by josemduarte** [comment]
Yes. As an alternative we could add this to biojava 4.2.x and call the method from `CrystalBuilder`, then we'd need another bugfix release. 

In biojava 5.0-SNAPSHOT the `expandNcsOps` is already there in `org.biojava.nbio.StructureTools`.
