### ISSUE TITLE
Improve the molecular potato

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#12]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Wednesday Apr 09, 2014 at 16:58 GMT_
_Originally opened as https://github.com/eppic-team/eppic-wui/issues/6_
---

The pymol color-by-entropy surface PSE files (a.k.a. molecular potatoes) are great for looking at things visually, but still not good enough. One possibility for improvement would be to display the interface PSEs as "cartopotatoes" i.e. one side potato and one side cartoon (perhaps still with core residues as sticks). From that one can get a good idea of the interface and the conservation around it. One thing still to think about is what to do about heterologous interfaces. For isologous it's clear that showing the potato on one side is all one needs, but for heterologous one would want to see the potato on either side.

Any ideas? The code to produce them is pretty easy to hack, it's all in the PymolRunner class in the eppic project.

**Comment by sbliven** [comment]
Solved by the pymol plugin

**Comment by josemduarte** [comment]
And by surface rendering in NGL
