### ISSUE TITLE
Warning about very old release dates

### ISSUE THREAD

**Issue by gcapitani** [eppic-team/eppic#122]
Another useful piece of info that can be shown in the top panel is the release date of an entry, which is stored in table PdbInfo. It could be shown after Resolution, so for 2trx:

Experimental Method X-RAY DIFFRACTION    Space Group C 1 2 1    Resolution 1.7 Å     Release Date     1991-10-15

**Comment by josemduarte** [comment]
While release date is important and can provide some valuable information, I think we have to be a bit careful about over-crowding the top panel with header data. Some arguments against it:

- the whole thing becomes less readable with so much text
- the line is likely to become too long for small screens
- why release date and not deposition date? should we have both? the argument can go on for lots of other pieces of header data (e.g. authors, publication link, ... )
- the more we add up there, the less space we have for the rest of the panel

**Comment by kumar-physics** [comment]
I agree with @josemduarte . Don't overcrowd the panel. Eppic has very neat and clean web interface and we should maintain that. After reading the comments, I am curious and checked the alpha version. Its looks wonderful. Its defiantly an upgrade from version 2 to 3. While I was testing ,it crashed. May be someone working on that or due its due to me. I am not sure, what caused the crash. The entry caused this problem is 4hnk .I try to view the unit cell and it got hanged. Please check that. I will be happy to test and report bugs :)

**Comment by gcapitani** [comment]
@josemduarte @kumar-physics I see your concerns, and I agree that there is a danger of overcrowding the top panel and the page. The release date is valuable for the user to see,
for instance, if an entry belongs to the early days of structural biology and may have been determined or refined with obsolete approaches. However, it is for sure not fundamental information, and it can be dispensed with. The idea here is to test how it looks like on the panel and keep it only if it does not impact too much with regard to the concerns outlined above. Does this sound reasonable?
@kumar-physics I restarted jetty on the dev server and tried 4hnk (unit cell), it worked fine.

**Comment by gcapitani** [comment]
Thinking more about it, since the use of the release date here is to warn the user about very old entries, a better way to go is to issue a warning. If the entry was released earlier than, say, 1995, a warning would appear in the top panel (as it does now for _e.g._ High R-free), saying something like:
"Very old deposition, more recent entries of the same structure may be available".
This way, additional space in the top panel is used only when needed (in the order of 1% of the cases).

**Comment by sbliven** [comment]
I would argue against warning about entries prior to a fixed date. If we are worried about low-quality structures, we should instead display a warning if R-free is missing (e.g. 1mbn), similar to the one we do for high R-free (e.g. 5D5G). If we want to indicate that newer structures are available, we can check for newer/better structures among the similar structures and display a warning if any are found. I assume that most older structures would fall into one of these categories, but some older structures may be OK and some newer structures less so.

**Comment by sbliven** [comment]
If we really want all this information at our fingertips without clicking through to the PDB website, another option would be to have an info box pop up in response to a click or mouseover that would have detailed info about the structure.

**Comment by gcapitani** [comment]
@sbliven Good points about the downsides of warning about entries prior to a fixed date. A missing R-free warning is probably best. Also a good idea to prompt the user with a warning if newer structures are available.

**Comment by josemduarte** [comment]
The missing Rfree and old release date overlap a lot. But in any case I'd agree with @sbliven that it is a safer thing to base the warning on missing Rfree than on date. 

Should we close this issue then?

**Comment by gcapitani** [comment]
Yes, if by tomorrow there are no further comments or suggestions I'll close it.
