### ISSUE TITLE
Small improvements to ngl views of assemblies and interfaces

### ISSUE THREAD

**Issue by gcapitani** [eppic-team/eppic#124]
Currently ngl assembly views (but not interface views) display water molecules, which should not be the case. 

Both for assemblies and interfaces the background should be white instead of black.

The 3D Viewer selector still indicates 3Dmol.js instead of NGL. Also the tooltip for the selector should be modified accordingly (saying NGL viewer).

**Comment by gcapitani** [comment]
Another aspect to improve is the representation of core and rim residue side chains in interfaces: currently all residue atoms are shown, while the main chain atoms C, O and N (and main chain hydrogens when present) should be hidden.

**Comment by sbliven** [comment]
There is a 'sidechain' selector in NGL (http://arose.github.io/ngl/doc/#User_manual/Usage/Selection_language)

**Comment by josemduarte** [comment]
Any reason not to show waters? I like that they can be shown quite nicely with NGL. They can help interpreting things.

**Comment by gcapitani** [comment]
@josemduarte the rationale here, in addition to having a less crowded view, is that the chains of assemblies are shown in cartoon mode, which provides an overall idea of the fold and secondary structure, but no atomic details, while water molecules (if accurate) are at the atomic detail level and help interpretation the most if one can see their interaction details with the surface. The user wanting to do that can download the coordinates for detailed examination with a local viewer (most likely looking at water structure by displaying the protein in full-atom representation).
We do have ligands in ball-and-stick (so there is the same "mismatch" of detail with the chain cartoon) but they are arguably more important than water molecules for interpretation (e.g. cofactors).
This said, I am also fine with showing water molecules. We could also have two levels of detail, a cartoon "on the rocks" and a full representation with ligands and water molecules.

**Comment by josemduarte** [comment]
This relates to the issue of creating some user interface for controlling the NGL display, I've now created a new issue for that: #126 . Let's go for default without waters and having the option to show them in a button.

**Comment by gcapitani** [comment]
The sidechain display now appears to work OK and to be clean with the rare exception of C-term residues, where the OXT atom is considered sidechain by NGL and appears as detached sphere (e.g. interface 3 of 2trx). See https://github.com/arose/ngl/issues/145.

**Comment by josemduarte** [comment]
This looks good now, I'll close

**Comment by sbliven** [comment]
According to https://github.com/arose/ngl/issues/145 we should use the 'sidechainAttached' selector.

**Comment by gcapitani** [comment]
We also need to update to the newest NGL release (tag 0.7.1a). The default path (from rawgit) should be:

https://cdn.rawgit.com/arose/ngl/v0.7.1a/js/build/ngl.embedded.min.js

**Comment by altheaparker** [comment]
TODO still - update the ngl.embedded.min.js to the lastest (above link is out of date) but need to test it first.

**Comment by josemduarte** [comment]
As of today, the latest release is 0.9.3, see https://github.com/arose/ngl/releases/tag/v0.9.3
