### ISSUE TITLE
Multiple warnings in top panel

### ISSUE THREAD

**Issue by gcapitani** [eppic-team/eppic#129]
Currently the top panel issues only a warning at a time: for instance, entries 1bpd or 2b8k should have both a no R-Free warning and a low resolution warning, but the panel issues only the low resolution one.

**Comment by josemduarte** [comment]
I think it should be a single icon with a single box containing the text for the multiple warnings as a list.

**Comment by sbliven** [comment]
For each warning we currently have a title ("Low Resolution") and a description ("This is a low-resolution structure. The results may not be reliable"). I suggest the following:

- For single warnings, display the warning icon and title at the top of the page ("⚠️ Warning: Low Resolution"). Include the description as a tooltip.
- For multiple warnings, display the number of warnings at the top of the page ("⚠️ 2 Warnings"). Concatenate all descriptions together for the tooltip.

**Comment by gcapitani** [comment]
Btw at the moment the warnings are shown without warning icon, while there should be one.

**Comment by gcapitani** [comment]
We now have the icon displayed and also a provisional implementation of multiple warnings showing the list in the tooltip. Seems to work OK, keeping it open for possible improvements

**Comment by sbliven** [comment]
Looks good.
