### ISSUE TITLE
Mark disagreeing-with-authors predictions

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#13]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Friday May 30, 2014 at 14:02 GMT_
_Originally opened as https://github.com/eppic-team/eppic-wui/issues/9_

----

The disagreeing calls between eppic and authors annotation (in InterfaceClusterScore with method="authors" in db) could be marked somehow, perhaps with a simple '*' next to the final call

**Comment by josemduarte** [comment]
We should really do this at the Assembly level now that we have it

**Comment by gcapitani** [comment]
+1

**Comment by lafita** [comment]
Similar thread in #100 for **PDB1** assembly predictions.

**Comment by josemduarte** [comment]
Yes let's close this one then and keep #100
