### ISSUE TITLE
cell.cif files are not created correctly

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#130]
The cell.cif files that we create for lattice graph viewing in NGL contain a problem in the `symmetry.space_group_name_H-M` field naming (see https://github.com/biojava/biojava/issues/480). NGL then can't parse the files and doesn't display anything. I'll release a new biojava bugfix version to solve this problem. 

In the meantime I've added a new test (9ab01c31410cb549c1ecf3313522dbae9b175b9b) that for the moment will fail. 

(note that in dev server I've fixed 3hbx.cell.cif manually to check)

**Comment by sbliven** [comment]
Good catch. I'd assumed that this had been included in 4.2.2 and was just a caching problem.

After the release & version bump we should delete all the cell.cif files to force their regeneration.

**Comment by josemduarte** [comment]
Let's see if I can release 4.2.3 soon, our new jenkins server that does it with one-click is down right now...

In any case as a side-project, I'm playing with passing the unit cell creation to the client so that we can avoid this file altogether (as discussed in #94). If I make progress with that I'll let you know.

**Comment by josemduarte** [comment]
Now irrelevant thanks to #132. We'll update to biojava 4.2.3 as soon as we can anyway.
