### ISSUE TITLE
Add config file/directory path to all eppic executables

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#131]
The hard-coded config paths make it difficult to have multiple databases or eppic 3 runs installed simultaneously. For instance, it might be useful to have a jetty instance on dev serving a small database which can be quickly regenerated based on changes to eppic.Main, and another instance with a more complete but older database for UI testing.

Here are the config paths I am most concerned about:
- ~/.eppic.conf, used by CLI
- ~/eppic-db.properties, used by dbtools
- ~/server-config, used by wui

**Comment by josemduarte** [comment]
> ~/.eppic.conf, used by CLI

This one can be overridden at run-time by command line parameter `-g`

> ~/eppic-db.properties, used by dbtools

This one is indeed hard-coded, it should be easy to have a command line parameter to override it too

> ~/server-config, used by wui

Also hard-coded. This one is a whole dir of config files, not just a single file. In this case it is not really possible to pass a command line parameter (at least I'm not aware how to do that with a war). But we _can_ pass a system property to the JVM (`-D`). I'd propose to have a top level `~/eppic-server-config` (still hard-coded) and then subdirs of it representing config profiles. We'd then pass the subidr name with `-DeppicConfigProfile=myprofile`. Then `~/eppic-server-config/myprofile` would contain all the needed config files. We can then have as many config profiles as we want.

**Comment by sbliven** [comment]
@josemduarte Why would the profile method be preferable to passing -DeppicConfigDir=~/eppic-server-config/myprofile directly? Then you avoid any hard-coded paths.

**Comment by sbliven** [comment]
We could also decide to leave the hard-coded paths and just use docker to produce different profiles.

**Comment by josemduarte** [comment]
Agree about having full path in parameter... Don't like so much the use of docker for doing profiles, that feels like an overkill to a simple problem.

**Comment by josemduarte** [comment]
Done:
- for dbtools scripts: they now all use `-g` as the parameter to pass a config file, except for UserJobCopier that uses a `-c` (-g was take and I didn't want to break other scripts).
- for wui: the directory containing the config files must be passed with `-DeppicWuiConfigDir`. If nothing is passed an error will be logged and the application won't continue
