### ISSUE TITLE
Non-enantiomorphic SG warning

### ISSUE THREAD

**Issue by gcapitani** [eppic-team/eppic#133]
A nice-to-have warning is one about structures with non-enantiomorphic space groups. While PDB entries with such SGs tend to have the word racemic in the title, it is good to visually warn users that they are special in that their content is racemic and the interfaces can be mediated by chirality-changing operators that are not seen in the 65 "classic" enantiomorphic SGs of protein crystals.
The warning should be triggered by checking the SG record in the db (PdbInfo.spaceGroup) and should read: "Non-enantiomorphic space group: the structure contains a racemic mixture"). 
The tooltip would explain more: "This structure belongs to a space group possessing operators that change the chirality of an object: some of the listed interfaces are mediated by such operators".

**Comment by gcapitani** [comment]
Appears to work OK, more testing needed, keeping it open for the moment.

**Comment by josemduarte** [comment]
I've found an incorrect warning for entry 4nwp (space group R32). It seems that R32 is not in the new lookup list. 

Ideally we should try to do this through information stored in db (e.g. through a new field "isEnantiomorphic" in PdbInfo table or through the existing field "operatorType" in the Interface table). Anyway that's a lot of work, so let's keep what we have for now, just making sure that the list is complete.

**Comment by gcapitani** [comment]
Appears now to work OK.

**Comment by sbliven** [comment]
Works ok (checked 4rwc (P -1 ) and 4mgp (I -4 2 d))
