### ISSUE TITLE
Show 3 levels of call confidence with some highlighting

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#14]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Friday May 30, 2014 at 14:08 GMT_
_Originally opened as https://github.com/eppic-team/eppic-wui/issues/10_

---

Since some time (https://github.com/eppic-team/eppic/commit/b4e7a123b8fe3d9ab3cdc9aca20b768d629b90c0) there's some confidence values produced (based on having enough sequences or not). Three levels of confidence (high, medium, low) could be marked on the calls somehow. Perhaps with some light background colour?

Ideas welcome!

**Comment by josemduarte** [comment]
This is pending having a way to assign a confidence (the wui part of it is done). In the interest of completing the project on time I'll move it to 3.1 After all we don't even have this in 2.1.

**Comment by lafita** [comment]
I think we need to distinguish between two types of confidence. 

On the one hand, we have the confidence on the estimation of the evolutionary scores (entropies), which entirely depends on the number of sequences in the alignment. The general idea would be: the more sequences in the alignment, the more confident we are that the evolutionary scores are the ones we calculate.
This can be expressed as confidence intervals in the scores. More sequences, more sampling, the confidence intervals at, for example, 95% confidence, are shorter. For example, we would have a cs score of -1 with a confidence interval at 95% confidence of +-0.5, so the score could take values in (-1.5, -0.5). If we had more sequences, the interval would be +-0.1, so the score could take values in (-1.1, -0.9).
I will create a separate issue to discuss how we compute this confidence value for core-rim and core-surface scores.

On the other hand, there is a confidence associated with the call itself, which I believe is the one we would like to express here. This can be understood as how far from the threshold are the scores. If the scores are near the threshold (whatever confidence, as described above, in their estimation), any call (XTAL or BIO) is a low confidence call, while if the scores are far from the threshold, calls are high confidence. 
This confidence can be captured with a logistic regression classifier that assigns a probability value to each call. High confidence calls will have either high probability, or low probability, while borderline cases will have probabilities near 0.5.

My suggestion is that for the final call we show, as described in this issue, a different call label for different ranges of probabilities and we report the call probability as all the other scores. 
For the other score calls, we have to think how to translate the numeric confidence value into the different call labels.
