### ISSUE TITLE
Obtaining interface cluster information in assemblies

### ISSUE THREAD

**Issue by lafita** [eppic-team/eppic#147]
I would like to retrieve a list of the interface clusters present in an assembly and a list of all the interface clusters in the crystal, so that I can tell whether an interface cluster is present or not in the assembly.

So far, I have arrived at this point (code inside **Assembly**):

```java
// Obtain list of interface clusters present in this assembly
		List<StructureInterfaceCluster> ics = getEngagedInterfaceClusters();
		
		// For each interface cluster in the crystal tell if present or not here
		InterfaceEvolContextList iecl = getCrystalAssemblies().getInterfaceEvolContextList();
		for (int i = 0; i < iecl.size(); i++)
			bool p = ics.contains(iecl.get(i).getInterface().getCluster())
```

But I think it is wrong because the size of the InterfaceEvolContextList is not the number of clusters, but I could not get anywhere the number of clusters. 

@josemduarte and @sbliven do you have a better way to find this?

**Comment by lafita** [comment]
I realized that the **engagedSet** contains exactly this information, so I do not need to calculate anything. 

However, I have another question: do the indices of the **engagedSet** correspond to the map of `CombinedClusterPredictors` in the `InterfaceEvolContextList`? 

In other words, if I want to obtain the score of the interface cluster in the index `i` of the **engagedSet**, can I do the following:

```java
InterfaceEvolContextList iecl = getCrystalAssemblies().getInterfaceEvolContextList();
		
		// For each interface cluster obtain the probability
		for (int i = 0; i < engagedSet.size(); i++) {
			double p = iecl.getCombinedClusterPredictor(i).getScore();
		}
```

**Comment by josemduarte** [comment]
`InterfaceEvolContext.getCombinedClusterPredictor(clusterId)` takes an interface cluster id as the parameter, so as long as what you have is an interface cluster id then you can use it that way. You should be able to get the interface cluster ids from the `StructureInterfaceCluster`
