### ISSUE TITLE
Problems with assemblies enumerated via contracted graph

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#148]
After latest commits on `contractionIssue` branch to solve issue #48 (thanks @sbliven !), I've tried the full eppic run for 3ulu (7 entities, assembly enumeration is done on contracted graph) and it fails at one of the final steps: PDB biounit mapping.

The problem is that the interface cluster ids matched from the PDB biounit are based on the full graph. Those are then passed to the Assembly constructor which at that point only knows about the contracted graph and thus can't find all the interface cluster ids and fails.

As well as that problem we have a few other related problems in assemblies enumerated with contracted graph:
- the symmetry and stoichiometry reporting is wrong 
- the assembly diagram files are not correctly produced

I see 2 possible solutions here:
- convert the interface cluster ids referring to the full graph to those referring to the contracted graph, so that the PDB biounit matching works
- a more solid solution that would prevent other potential problems: at the end of the contracted assembly enumeration set the exposed graph back to the full graph, so that all downstream processes deal with the full graph which is what they expect

**Comment by josemduarte** [comment]
I'm going to reopen this issue. It looks like some problems remain in large heteromeric assembies, e.g. 4tub. The enumeration might be right for it but the symmetry, stoichiometry and assembly diagrams are all wrong. I fear the that the patch 179189e is not adding back all necessary edges from the full graph.

**Comment by lafita** [comment]
I think from the description that I can solve this, but I will not be able to take a loot at this until next week.

**Comment by lafita** [comment]
I have been looking at the code and I found it very complicated to understand. I have the idea of what should be done in my mind, but I did not see the way to modify the existing code to implement it (it seems to me that I should rewrite it from scratch). 

The idea would be:

1. Choose a subset of entities to contract: store a list of all the interface clusters between any two of them.
2. Compute the assemblies from the contracted graph and obtain a list of engaged interface clusters for each of them.
3. Add the interface clusters in step 1 to all the assemblies found in step 2.

This should also solve the problem mentioned in one of the tests:

> in the assembly reconstruction from the contracted graph to the full graph (see CrystalAssemblies.convertToFullGraph() ), we lose interface 8 (an induced interface). That's why the assembly here is 1,2,3

**Comment by josemduarte** [comment]
True the code is rather complicated sometimes. As a tip, the method to go from the contracted graph back to the full graph is `CrystalAssemblies.convertToFullGraph()`, which I implemented recently but didn't do a very good job. `TestContractedAssemblyEnumeration` contains some tests for this.

From the steps you mention above:
- 1 is done in `GraphContractor` (or partly at least). We store all interface cluster ids that we contract (retrievable with `GraphContractor.getContractedInterfClusterIds()`)
- 2 is done in `CrystalAssemblies.findValidAssemblies()`, by previously calling `latticeGraph.contractGraph()`
- 3 is what `CrystalAssemblies.convertToFullGraph()` should be doing

The problem right now is either in the logic in `CrystalAssemblies.convertToFullGraph()` or some issue in storing the interface cluster ids during graph contraction.
