### ISSUE TITLE
Integrate EPPIC explorer

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#149]
Integrate the EPPIC explorer as an IFrame into the main eppic site

- [ ] Add `eppic_explorer_url` property to the server.properties file
- [ ] ~Add 'Advanced Search' link to homepage, below 'Current Uniprot Version'~
- [x] Add 'Advanced Search'  to top menubar

Changes should be made in a new 'explorer' branch in git

**Comment by josemduarte** [comment]
It looks like some commits related to this went to master, is that intended? See 681eee8e620362f69893870c472269f26a6130d9 and 68206bfd176302f3fa3a0af62a180dd3d2c442aa

**Comment by lafita** [comment]
That was not intended, and @sbliven reverted them. They are now in the `explorerIntegration` branch.

**Comment by sbliven** [comment]
Adding the link to the homepage looked weird. Better to just have it in the top bar.

New feature:

- [ ] if the eppic_explorer_url is not set in the properties file, then do not show the Advanced Search links.

**Comment by lafita** [comment]
In the dev and production servers, the integration is not working. Although the EPPIC explorer is running in the servers, a **404** with the following message appears in the iFrame:

<pre>
Problem accessing /ewui/%22http://eppic01.psi.ch:8082%22/.
</pre>

Those **%22** symbols look strange to me, and isn't there something missing before the ewui?

**Comment by lafita** [comment]
Solved in the server.properties file
