### ISSUE TITLE
Fix web root prefix

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#152]
URLs should start with /ewui as they do in eppic 2. For instance, structures should be "/ewui/#id/2gs2".

Requests to the root ("/") should redirect to /ewui.

This is probably just a jetty config thing in web.xml.

**Comment by josemduarte** [comment]
I had a go at this some time ago. Notes about it are here: https://wiki.systemsx.ch/display/crk/Server+administration

Two subissues here:
- We want to serve the app under /ewui, so that URLs are as before
- We want that the root dir redirects to ewui so that users hitting eppic-web.org go straight to the app

**Comment by sbliven** [comment]
This is done fully with configuration files. First, set the `contextPath` to `/ewui`. Second, add a redirect for the root.

**eppic-base/webapps/ewui.xml:**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">
 
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/ewui</Set>
  <Set name="war"><Property name="jetty.webapps"/>/ewui.war</Set>
  <Set name="virtualHosts">
    <Array type="java.lang.String">
      <Item>pc11467</Item>
      <Item>pc11467.psi.ch</Item> 
      <Item>eppic-web.org</Item>
      <Item>www.eppic-web.org</Item>
    </Array>
  </Set>
  <!-- Allow symbolic links  -->
  <Call name="addAliasCheck">
   <Arg><New class="org.eclipse.jetty.server.handler.AllowSymLinkAliasChecker"/></Arg>
  </Call>
</Configure>
```

**eppic-base/webapps/root_context.xml:**
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Mort Bay Consulting//DTD Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">

<Configure class="org.eclipse.jetty.server.handler.MovedContextHandler">
    <Set name="ContextPath">/</Set>
    <Set name="NewContextURL">/ewui</Set>
    <Set name="Permanent">true</Set>
    <Set name="DiscardPathInfo">true</Set>
    <Set name="DiscardQuery">true</Set>
</Configure>
```

It appears that the names of the config files are unimportant.
I'll update the wiki as well.
