### ISSUE TITLE
Show a column in the assemblies table of the WUI for probability score

### ISSUE THREAD

**Issue by lafita** [eppic-team/eppic#153]
Since the assemblies table is simpler than the interfaces table, we could introduce a new column with the probability score for each assembly, together with the call. 

I think this would be beneficial for the interpretation of the results from a user perspective, since it is an easy to understand score and can be useful to detect errors in assembly enumeration, and others. We could also show the confidence stars next to the final call, like for interfaces #14.

**Comment by josemduarte** [comment]
I like the idea, both the new column and showing the stars. We have to think how to do both the stars and the PDB biounit call (an icon by the EPPIC call at the moment). Perhaps the PDB biounit icon could be in another column.

**Comment by lafita** [comment]
The confidence stars are now shown for assemblies: 32819dd

**Comment by sbliven** [comment]
Looks like this is fixed now.

**Comment by lafita** [comment]
We agreed that the probability column is needed to highlight the advantages of the prediction confidences. 

In the previous version of the method, the EPPIC scores were not a relevant information, since they were only used to compute the binary call. Differences below or above the threshold could not be easily interpreted, and that is why they appeared in the tooltip only.

However, in the new version of the method, a column with the scores for all assemblies is needed to easily identify those assemblies with relevant probability of being biological, in cases where there is more than one. Using the tooltip for that is not enough, because the user would have to mouse over each call to see it.
