### ISSUE TITLE
Show a message with the call reason for assemblies

### ISSUE THREAD

**Issue by lafita** [eppic-team/eppic#157]
Similar to how interface calls are explained, there should be a text message with the explanation of the call for assemblies. It could be something like:

- Highest probability assembly of being biologically relevant found in the crystal, for BIO calls
- Another assembly in the crystal has a higher probability of being biologically relevant, for XTAL.

Additionally, we could also show the call confidence stars #14. All of this is additional to showing the actual probability for each assembly (score) in another column, issue described in #153.

**Comment by josemduarte** [comment]
Looks good! thanks @altheaparker ! (I've added a dummy message to 1smt for testing). I'll close this one, the stars feature is described in #153
