### ISSUE TITLE
More descriptive message for FINAL call reason

### ISSUE THREAD

**Issue by lafita** [eppic-team/eppic#158]
At the moment we show a very cryptic message for the FINAL call reason:

- For BIO: P(BIO) = 0.98 > 0.5
- For XTAL: P(BIO) = 0.15 < 0.5

I wrote that, because I thought there was not much space. Considering that the message for the other scores is more texty, we can change it to something like:

- For BIO: Probability of the interface being biologically relevant is 0.98.
- For XTAL: Probability of the interface being biologically relevant is 0.17.

Should we include the threshold at all? It is more or less obvious that a probability higher than 0.5 means the statement is more likely to happen than not (positive log-odds), while a probability lower than 0.5 means that the statement is less likely to happen than not (negative log-odds).

Other suggestions?

**Comment by josemduarte** [comment]
I like the more descriptive text. I wouldn't include the threshold, that's rather obvious.
