### ISSUE TITLE
Upgrade to mysql 5.6 worth it?

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#16]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Monday Jun 02, 2014 at 16:11 GMT_
_Originally opened as https://github.com/eppic-team/eppic-wui/issues/12_

---

We use 5.1.x at the moment.
It seems that 5.6 could have better performance especially if properly configured to do more multi-threaded stuff. These guys (in 2011!!) recommend it:
http://www.mysqlperformanceblog.com/2011/08/15/whats-the-recommended-mysql-version/

There are official yum repos at dev.mysql:
http://dev.mysql.com/downloads/repo/

**Comment by sbliven** [comment]
This shouldn't require any code changes, right? Why not!

**Comment by sbliven** [comment]
We might as well use 5.7.

**Comment by josemduarte** [comment]
Or latest MariaDB?

**Comment by sbliven** [comment]
Isn't that a drop in replacement for mysql?

**Comment by josemduarte** [comment]
I'll move this forward too. Nice to have but not necessary at all.

**Comment by sbliven** [comment]
This is more an IT issue than something relating to the EPPIC code.
