### ISSUE TITLE
Consistent URLs and add single interface highlighting

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#165]
We need to make clearer URLs for the various types of search results. Note that the /ewui prefix assumes #152 is finished.

- [X] Structure (All assemblies): `/ewui/#id/<jobid>`
- [X] All Interfaces: `/ewui/#interfaces/<jobid>`
- [x] Single Interface: `/ewui/#interfaces/<jobid>/<interfaceid>`
    - Shows all interfaces but selects the specified one
- [x] Single Assembly: `/ewui/#assembly/<jobid>/<assemblyid>`
    - Currently routed from `/ewui/#interfaces/<jobid>/<assemblyid>`, which conflicts with the single interface
- [X] All clusters: `/ewui/#clusters/<jobid>`
- Single cluster: `/ewui/#clusters/<jobid>/<clusterid>`
    - Not currently needed since no cluster search results

_Edit: changed for single Assembly, removed single cluster page_

**Comment by lafita** [comment]
About searching interface clusters, what we are currently doing is an option to the user to use only cluster representatives. This options filters all interfaces down to one interface per cluster, the representative being the biggest one.

**Comment by sbliven** [comment]
@lafita In that case, we should implement the single cluster URL and highlight all member interfaces. We can get the clusterId for the interface result in R?

**Comment by sbliven** [comment]
+1 to @altheaparker's suggestion of `#assembly` (singular), since it only shows one assembly.

**Comment by sbliven** [comment]
Also we decided not to implement the 'single cluster` highlighting.
