### ISSUE TITLE
Text wraps around when there is a space group warning

### ISSUE THREAD

**Issue by altheaparker** [eppic-team/eppic#168]
When it says Interface Analysis of: Assembly 5 in
3hbx  *Warning: Non-standard space group*
and the browser is not very wide, the text does not wrap around properly. 
http://localhost:8081/ewui/#assembly/3hbx/5

**Comment by lafita** [comment]
@altheaparker fixed that by showing only the red **Warning** message, omitting the display of the descriptions, which is only shown in the tool-tip.
