### ISSUE TITLE
Hide "Advanced Search" link when no explorer URL is configured

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#169]
If the eppic_explorer_url is blank, don't display the "Advanced Search" link in the top menu

**Comment by sbliven** [comment]
This is actually quite complicated in GWT.

You would think It would be a simple matter. The obvious java code would be to check the URL and only produce the links if its set. E.g., in `NavigationPanel.createLinksPanel()`:
```
String explorerUrl = ApplicationContext.getSettings().getEppicExplorerUrl();
if(explorerUrl != null && !explorerUrl.isEmpty() ) {
	linksContainer.add(advancedSearchLink, new HorizontalLayoutData(-1,1));
	linksContainer.add(createBreakLabel(), new HorizontalLayoutData(-1,1));
}
```

However, the doesn't work because this whole function gets compiled into javascript by GWT, so it doesn't have access to the server settings when the code executes on the client. The link itself requires a RPC callback to figure out the correct URL on the server.

According to [this SO question](http://stackoverflow.com/questions/7469187/how-to-tackle-changing-properties-on-the-clientside-in-gwt-applications) the correct way to implement this is a [dynamic host page](http://www.gwtproject.org/articles/dynamic_host_page.html) (basically a servlet) to serve your whole app.

I've concluded that the most practical solution to this is "comment out those two lines in NavigationPanel and recompile". I've written some non-working attempts to [sbliven/fix169](https://github.com/sbliven/eppic/tree/fix169), which I am now abandoning.

**Comment by josemduarte** [comment]
We do this kind of passing of properties from server to client through `ApplicationSettings` which are then passed to `ApplicationContext` and retrieved from the client with `ApplicationContext.getSettings()`. We do that for many properties already, I'm giving it a try now to see if the solution works.

**Comment by josemduarte** [comment]
I got it  working! I tested it in dev server and it seems fine.
