### ISSUE TITLE
Theming now easier with GXT 3.1

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#17]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Monday Jun 16, 2014 at 09:43 GMT_
_Originally opened as https://github.com/eppic-team/eppic-wui/issues/15_
---

See http://docs.sencha.com/gxt/3.1.0-beta/ui/theme/GeneratingThemes.html
This might mean that some of the fonts (and other) customisation we did could be more easily (and more reliably) done now. 
I have no clue how much effort it requires though. They claim that the new theme generator is very easy to use.

**Comment by sbliven** [comment]
Seems like something to keep in mind for new pages, but doesn't need to be changed on old pages.

**Comment by josemduarte** [comment]
Yes indeed. I'd say by now it would be better to rewrite the client side in some other framework than do some complicated theming customisation in gxt.
