### ISSUE TITLE
Switch to "All interfaces" view does not work

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#172]
At the moment if one clicks in "all interfaces" the view switches for a moment to then come back to the assemblies view. I think the problem came in commits 268614d9c811f9ecf85e6b3f7d7199c7f3c45434 and ea9f31641d7124993d188319c8ebf0a0c0b40ddb

**Comment by lafita** [comment]
Me and Allie will take a look on Tuesday. Thanks!
