### ISSUE TITLE
Update help and FAQ documentation

### ISSUE THREAD

**Issue by lafita** [eppic-team/eppic#179]
We need to update the following **FAQ** sections:

- [x] **How do I know if a prediction is reliable? Does EPPIC produce confidence values?** We need to indicate that the confidence of the prediction is reported as a probability and that we show the stars to represent high confidence predictions both for interfaces and assemblies (already described in Help though).
- [x] **How is the final call predicted?** We no longer use the consensus voting, but the probability of an interface being biological.
- [ ] Come up with a few questions for assemblies, since there are none at the moment.

And the following **Help** section:

- [x] **The assemblies table**: explain the probability by hovering over the call and the confidence stars as in the interfaces.

**Comment by josemduarte** [comment]
Well spotted and nice text! Would you mind adding that to the faq.html file?

**Comment by lafita** [comment]
Yes, I can do that!

**Comment by josemduarte** [comment]
I've added a few corrections to FAQ and help. There's still not much about assemblies in FAQ, a few more questions could be added.

**Comment by josemduarte** [comment]
I've added a few more corrections and a new question. Things can still be improved later, I'll move this forward to 3.0.2
