### ISSUE TITLE
Show a more interesting example

### ISSUE THREAD

**Issue by lafita** [eppic-team/eppic#182]
Our current example **1YNU** is not that interesting from an assembly point of view, because it has only two possible dimers. 

There are other structures more interesting from the biological assembly assignment point of view, and better examples for the capabilities of **EPPIC**.

I propose **3HBX**, a D3 assembly predicted with high confidence. What do you think?

**Comment by josemduarte** [comment]
Yes I was thinking about changing the example too. I'd go for some high confidence high Dn symmetry. Perhaps not 3hbx because it's very large and does have some lag in loading especially in a slow connection. Any other candidates?

**Comment by josemduarte** [comment]
BTW this can be changed any time, it's set in config file

**Comment by lafita** [comment]
Ok, then let's use this issue to propose entries!

**Comment by josemduarte** [comment]
5lsr looks good and loads fast. Our prediction coincides with PDB's annotation, we should double check there's experimental data for it.

**Comment by josemduarte** [comment]
Homolog 4ht5 was solved much earlier and it looks good too. I'll switch the example to that one. Please feel free to change if you find something better!
