### ISSUE TITLE
Server goes down when a user requests downloading multiple files 

### ISSUE THREAD

**Issue by lafita** [eppic-team/eppic#189]
If the User is not whitelisted, even though the following message appears in the browser:

> Input values are incorrect: Too many submissions for IP=???.??.???.??? - current number of submissions: 529 equals allowed submissions per 24h: 100 - Please contact the administrator if you want to increase number of allowed submissions or try after: May 24, 2017 12:19 PM

If the User still tries to download more files from the command line, for example, the server goes down.

**Comment by lafita** [comment]
The server also goes down even if the number of requests do not exceed the limit of 100. 

A strange: `Error while loading settings` also appears.

4 java threads are running at 100%.

**Comment by lafita** [comment]
When trying to restart the server, it fails with:

<pre>
There is insufficient memory for the Java Runtime Environment to continue.
Cannot create GC thread. Out of system resources.
</pre>

**Comment by lafita** [comment]
Could it be a problem with wget? This page can be seen and downloaded in the browser, but the following does not work:

`wget http://www.eppic-web.org/ewui/ewui/dataDownload?type=xml&id=1e2l`

<pre>
--2017-05-23 20:38:48--  http://www.eppic-web.org/ewui/ewui/dataDownload?type=xml
Resolving www.eppic-web.org... 192.33.120.69
Connecting to www.eppic-web.org|192.33.120.69|:80... connected.
HTTP request sent, awaiting response... 412 Input values are incorrect: Please provide comma seperated values of either PDB-Codes or EPPIC-JobIds with &id=
2017-05-23 20:38:48 ERROR 412: Input values are incorrect: Please provide comma seperated values of either PDB-Codes or EPPIC-JobIds with &id=.
</pre>

**Comment by lafita** [comment]
Oh I see, I had a typo so that everything after the `?` symbol is not read by `wget`, and then the server is waiting for a response. Because I do that a lot of times, the server has many requests waiting and it goes down.

Is that a potential problem and should we do something about it?

**Comment by josemduarte** [comment]
Yes you need to use quotes around the url, or otherwise the ampersand is interpreted by bash.

Anyway I fear that the problem could be that the request is quite demanding since we go straight to the db without any caching. In any case we at least know how to reproduce the problem, so with this data we can do some debugging.

**Comment by josemduarte** [comment]
I've had a quick test and things look ok now in the RCSB cloud hosting. I'll close.
