### ISSUE TITLE
Drop the hard/soft identity cutoffs?

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#2]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Tuesday May 06, 2014 at 12:25 GMT_
_Originally opened as https://github.com/eppic-team/eppic-cli/issues/5_
---

I think it can be a good idea to drop the double cutoff for seq identity, some reasons:
1) My feeling is that it only lowers the accuracy by using below-standard-reliability alignments (see our famous benchmarks). Why risking it? especially when we know there are bucket-loads of new data coming. I think it is better to lose coverage than to have lower accuracy. If we do give a prediction we should do it as good as possible and always with the same "measure" so that things are more consistent and comparable.
2) It does not help to the benchmarking over time, since it produces instability in the homolog selection over time. Often an entry that in uniprot i has 10 homologs, then in uniprot i+1 it has 100 homologs simply because the cutoff was relaxed. That really doesn't help the predictions and confuses us a lot, especially when studying things over time. An example is 1wrb: in UniProt 2013_08 it has 10 homologs (using 60% cutoff), in 2013_09 it has 106 (because 55% cutoff was used)

TO DO:
We could check from the new bio and xtal PDB-wide datasets what is the accuracy of results for those entries that used 60% cutoff and those that used 50%. That might give us an idea of how it is behaving.

**Comment by sbliven** [comment]
Let's keep the cutoffs.
