### ISSUE TITLE
Setting up error and downtime pages

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#20]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Wednesday Sep 03, 2014 at 13:26 GMT_
_Originally opened as https://github.com/eppic-team/eppic-wui/issues/23_
---
### Downtime page in separate server

I've got an AWS instance set up with jetty and everything. We can use it as a server-down message holder when we go for scheduled downtime or the server goes down for some time.

TODO:
- create a static html page with the message
- make jetty send a 503 code for the search engines (see http://moz.com/learn/seo/http-status-codes)
- distribute the AWS key so that everyone can log and configure it
### 404 custom page

This must be easy to do with some jetty setting

**Comment by sbliven** [comment]
I guess this won't be maintained now.
