### ISSUE TITLE
Extra residues appear in some assembly files

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#200]
E.g. 3uko, assembly 5. 

<img width="622" alt="screen shot 2017-12-06 at 10 27 44 pm" src="https://user-images.githubusercontent.com/6000474/33701684-bbc265ba-dad4-11e7-94eb-0ba49e5b94d9.png">

**Comment by lafita** [comment]
The residue is duplicated in the assembly mmcif file:

<pre>
ATOM   2570  N  N   A SER A_0 1 326 ? 8.669   -19.296 6.468   0.50 0.82   ? ? ? ? ? ? 327 SER A_0 N   1
ATOM   2571  C  CA  A SER A_0 1 326 ? 9.943   -19.991 6.692   0.50 0.82   ? ? ? ? ? ? 327 SER A_0 CA  1
ATOM   2572  C  C   A SER A_0 1 326 ? 10.368  -20.912 5.541   0.50 0.82   ? ? ? ? ? ? 327 SER A_0 C   1
ATOM   2573  O  O   A SER A_0 1 326 ? 11.490  -20.807 5.026   0.50 0.82   ? ? ? ? ? ? 327 SER A_0 O   1
ATOM   2574  C  CB  A SER A_0 1 326 ? 9.843   -20.831 7.974   0.50 0.82   ? ? ? ? ? ? 327 SER A_0 CB  1
ATOM   2575  O  OG  A SER A_0 1 326 ? 8.655   -21.596 7.939   0.50 0.82   ? ? ? ? ? ? 327 SER A_0 OG  1
ATOM   2576  N  N   B SER A_0 1 326 ? 56.444  19.732  62.537  0.50 20.58  ? ? ? ? ? ? 327 SER A_0 N   1
ATOM   2577  C  CA  B SER A_0 1 326 ? 57.685  20.498  62.769  0.50 19.99  ? ? ? ? ? ? 327 SER A_0 CA  1
ATOM   2578  C  C   B SER A_0 1 326 ? 58.131  20.565  64.231  0.50 18.45  ? ? ? ? ? ? 327 SER A_0 C   1
ATOM   2579  O  O   B SER A_0 1 326 ? 59.223  20.107  64.595  0.50 22.26  ? ? ? ? ? ? 327 SER A_0 O   1
ATOM   2580  C  CB  B SER A_0 1 326 ? 57.517  21.949  62.280  0.50 24.22  ? ? ? ? ? ? 327 SER A_0 CB  1
ATOM   2581  O  OG  B SER A_0 1 326 ? 57.696  22.039  60.877  0.50 31.19  ? ? ? ? ? ? 327 SER A_0 OG  1
</pre>

I think it is a problem with residues with alternative conformations. The original PDB file:

<pre>
ATOM   2527  N   LYS A 326      55.727  16.583  61.481  1.00 18.01           N
ANISOU 2527  N   LYS A 326     2390   1771   2681   -498     78   -110       N
ATOM   2528  CA ALYS A 326      55.179  17.728  62.205  0.50 17.64           C
ANISOU 2528  CA ALYS A 326     2291   1301   3111   -704    163    244       C
ATOM   2529  CA BLYS A 326      55.151  17.619  62.339  0.50 18.55           C
ANISOU 2529  CA BLYS A 326     1942   1791   3313   -370    155     -3       C
ATOM   2530  C   LYS A 326      56.353  18.431  62.842  1.00 19.92           C
ANISOU 2530  C   LYS A 326     2262   2189   3115   -499   -109     48       C
ATOM   2531  O   LYS A 326      57.167  17.841  63.531  1.00 21.80           O
ANISOU 2531  O   LYS A 326     2774   2215   3293   -592   -392    298       O
ATOM   2532  CB ALYS A 326      54.149  17.307  63.236  0.50 21.31           C
ANISOU 2532  CB ALYS A 326     2700   2969   2427   -465     23    -20       C
ATOM   2533  CB BLYS A 326      54.424  16.916  63.544  0.50 23.31           C
ANISOU 2533  CB BLYS A 326     2672   2741   3444    -68    434     45       C
ATOM   2534  CG ALYS A 326      52.844  16.934  62.615  0.50 19.53           C
ANISOU 2534  CG ALYS A 326     2195   2291   2934    -39    -27    -93       C
ATOM   2535  CG BLYS A 326      53.412  15.806  63.200  0.50 22.86           C
ANISOU 2535  CG BLYS A 326     2571   2314   3798    489      0     31       C
ATOM   2536  CD ALYS A 326      51.854  16.610  63.685  0.50 18.70           C
ANISOU 2536  CD ALYS A 326     1864   2243   2997   -934   -327   -175       C
ATOM   2537  CD BLYS A 326      52.969  14.981  64.429  0.50 23.89           C
ANISOU 2537  CD BLYS A 326     2102   2883   4090    299   -107    203       C
ATOM   2538  CE ALYS A 326      50.450  16.518  63.124  0.50 21.47           C
ANISOU 2538  CE ALYS A 326     2136   2872   3149  -1449   -684   -212       C
ATOM   2539  CE BLYS A 326      54.075  14.220  65.239  0.50 17.73           C
ANISOU 2539  CE BLYS A 326     1504   1533   3699   -234    282    346       C
ATOM   2540  NZ ALYS A 326      49.455  16.451  64.226  0.50 26.77           N
ANISOU 2540  NZ ALYS A 326     2107   4399   3662  -1312   -819   -348       N
ATOM   2541  NZ BLYS A 326      54.406  12.844  64.819  0.50 28.11           N
ANISOU 2541  NZ BLYS A 326     3670   1855   5154   1031    184   1109       N
</pre>

**Comment by josemduarte** [comment]
That must be it! thanks for investigating! It looks like it only happens for assemblies and not for interfaces. So something is different in the way we do symmetry mates in either case.

**Comment by josemduarte** [comment]
5d14 assembly 2, is a good and small test case

**Comment by josemduarte** [comment]
It turned out to be an issue in biojava, see https://github.com/biojava/biojava/issues/715

**Comment by josemduarte** [comment]
Now fixed, will go out in 3.0.4
