### ISSUE TITLE
Link to sequence cluster missing!

### ISSUE THREAD

**Issue by kumar-physics** [eppic-team/eppic#211]
What happened to the link to similar structure. Is sequence cluster module broken?

**Comment by josemduarte** [comment]
After the last re-computation with 3.0.4, I tried running blastclust in Ubuntu 16.04 but it dies with a segmentation fault :(

Without any updates to blastclust for a long time, I fear that the software is reaching its lifetime.

**Comment by kumar-physics** [comment]
I miss that option. When ever I wanna find similar structures, I come to EPPIC. I could go to PDB and get the same information, but I like the EPPIC's way of displaying the output in a clean table. Are there any alternate for blastclust?

**Comment by josemduarte** [comment]
https://github.com/soedinglab/MMseqs2 looks like a good candidate to replate it. I'm doing some research on that.

**Comment by josemduarte** [comment]
Now fixed by using mmseqs2
