### ISSUE TITLE
altloc records are sometimes duplicated in the output file

### ISSUE THREAD

**Issue by biocryst** [eppic-team/eppic#220]
A small test case to reproduce:
1. Open 1GVD structure, http://eppic-web.org/ewui/#id/1gvd
2. Select 3D viewer mmCIF and download the assembly file (it's a monomer).
3. For some residues (e.g., R102, K105) alternative location 'A' is listed twice, for some (P112, K113) once.
There is no apparent difference for these residues in the original mmcif file (https://files.rcsb.org/view/1GVD.cif).

**Comment by josemduarte** [comment]
Now fixed, by not writing out the other altlocs but instead only one alternative location (which can be a mix of '.' and 'A' locations as in R102 in 1GVD).

Notice that the difference of R102 and P112 in 1GVD is that in R102 only some atoms are in alt location with some common atoms in default ('.') whilst in P112 all atoms are in either 'A' or 'B'.

See also https://github.com/biojava/biojava/issues/778
