### ISSUE TITLE
Browser autocomplete (e.g. of email) broken for main form

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#27]
Firefox auto-suggests completions for fields like the email address. These can normally be chosen by typing down to select the desired completion and pressing enter, or by clicking the proper element.

This doesn't work on the EPPIC submission form. Typing enter will sometimes give an error (e.g. invalid email address), or is sometimes ignored.

Mac OS 10.9, Firefox 33.1

**Comment by sbliven** [comment]
Low priority

**Comment by sbliven** [comment]
GWT bug; wontfix

**Comment by altheaparker** [comment]
To reproduce:
Open firefox browser and enter a valid email address and press submit. Then you should see this email choice appear in the suggestions list next time you start to enter it. When you start to type your email address and see the suggestion appear, and you try to select it by pressing enter, it submits the form at this point already which results in errors (you should first validate the email before sending the form!)

There is another issue where the email value returns to a previous value, and the tooltip reports an invalid email address (not being what is currently entered) but this is not a severe problem.

We need the enter button to submit the form. This is likely not possible to solve in GWT and is OK as is.
