### ISSUE TITLE
Isologous/heterologous detection

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#3]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Friday May 16, 2014 at 09:48 GMT_
_Originally opened as https://github.com/eppic-team/eppic-cli/issues/6_

----

Detection of isologous/heterologous character (see Monod 1965 or http://en.wikipedia.org/wiki/Heterologous) of interfaces should be easy to implement (independent of the infinite interface detection we do now from crystallographic operators). It can be done in 2 ways:
- symmetry detection: if C2 isologous, otherwise heterologous
- contact overlap: compare an interface to its inverse in terms of contact overlap, if they don't match it's a heterologous (e.g. try 1zz0 interface 5, a heterologous case)

**Comment by josemduarte** [comment]
This is implemented for 3.0 and in db model. We still require a way to mark the isologous interfaces in the web gui. Ideas?

**Comment by gcapitani** [comment]
We could produce a very simple shape (e.g. a "comma" or a "L") and arrange two copies of it to form 
an "isologous" icon and a "heterologous" icon. I think it is important to keep the two icons as simple and clear as possible.
