### ISSUE TITLE
Drop the hard area limits?

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#33]
This is an ad-hoc rule that doesn't really improve performance much.

For instance these are queries I did some time ago:

__Low hard area limit__
```sql
select i.uid,i.interfaceId,i.pdbCode,i.area,s.callName,s.method,s.score 
from InterfaceScore s 
join Interface i on s.interfaceItem_uid=i.uid 
join InterfaceWarning w on w.interfaceItem_uid=i.uid 
where method="eppic-cs" and w.text not like '%peptide%' and i.area<400 and score<-1 and score>-1000;
```
662 rows (includes some peptides too, those having multiple warnings)

```sql
select i.uid,i.interfaceId,i.pdbCode,i.area,s.callName,s.method,s.score 
from InterfaceScore s 
join Interface i on s.interfaceItem_uid=i.uid 
join InterfaceWarning w on w.interfaceItem_uid=i.uid 
where s.method="eppic-cs" and w.text not like '%peptide%' and i.area<400 and s.callName="bio";
```
662 rows (including as above some peptides)

__High hard area limit__
```sql

select i.uid,i.interfaceId,i.pdbCode,i.area,s.callName,s.method,s.score 
from InterfaceScore s 
join Interface i on s.interfaceItem_uid=i.uid 
where method="eppic-cs" and i.area>2200 and score>-1 ;
```
1351 rows

```sql
select i.uid,i.interfaceId,i.pdbCode,i.area,s.callName,s.method,s.score  
from InterfaceScore s 
join Interface i on s.interfaceItem_uid=i.uid  
where method="eppic-cs" and i.area>2200 and s.callName="xtal";
```

1395 rows

Full count of all scored interfaces:
```sql
select count(*) from InterfaceScore where method="eppic-cs";
```
797543

The counts are really tiny (total number of interfaces is ~800,000, with ~100,000 bio), thus an indication that the ad-hoc rule could go without any problem. I'd rather use the extreme areas as a confidence measure.

**Comment by kumar-physics** [comment]
The numbers mentioned are not correct , because the list contains redundant entries due to two the use of two join. If you use group by pdhcode,interfaceId then you will get unique list. EPPIC explorer actually does it in correct way.  That's why we get smaller counts in EPPIC explorer.

**Comment by kumar-physics** [comment]
Here are the screen shots for the same queries using EPPIC explorer
Low area limit 432
![low](https://cloud.githubusercontent.com/assets/5636184/5956715/16d2687e-a7b1-11e4-954e-178ef46203a3.png)

High area limit 1086
![high](https://cloud.githubusercontent.com/assets/5636184/5956726/3211bcb6-a7b1-11e4-9113-b5d861943d0a.png)

Note: the filter on core surface score is applied not only on the final score, but also on both sides.

**Comment by kumar-physics** [comment]
Here are the actual numbers
mysql> select count(*) from EppicTable where area>2200 and cscall='xtal';
+----------+
| count(*) |
+----------+
|     1575 | 
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from EppicTable where area>2200 and crcall='xtal';
+----------+
| count(*) |
+----------+
|     2910 | 
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from EppicTable where area<400 and crcall='bio';
+----------+
| count(*) |
+----------+
|     1450 | 
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from EppicTable where area<400 and cscall='bio';
+----------+
| count(*) |
+----------+
|     1152 | 
+----------+
1 row in set (0.00 sec)

**Comment by lafita** [comment]
Were the hard area limits dropped in the end? 

Interface area could be included in a logistic regression classifier to account for the high probability of being XTAL with low area and being BIO for high area.

**Comment by josemduarte** [comment]
> Were the hard area limits dropped in the end?

Yes, see commit f75cd82b9c2a213e9e7c5bbf5d370697092949ed
