### ISSUE TITLE
Drop nopred calls for not enough reliable residues?

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#34]
Rethinking in this again the not-enough-reliable residues (misaligning to uniprot ref) should not be used for the call but rather just for warnings and eventually for confidence estimation.

An example where the output doesn't make so much sense is 4dom: 1st interface gets score from one side only because the other side has a few mutations in the core residues. The actual cs scores for both sides are quite different (-1.08, 0.16) and it would have been averaged. With current situation only left side is taken and a bio is called. That seems wrong: either I'd like a nopred for the whole interface or a normal prediction with warnings.

**Comment by sbliven** [comment]
Is this fixed?

4dom seems to have changed quite a bit with the current database (cs -.62 vs -.13 on the dev server), so maybe we need another example.

**Comment by josemduarte** [comment]
Yes, most likely the example was referring to 2.1. We'll need to find a better example, but the issue is important (though only affecting some edge cases). In any case if we are pressed by time we can move it eventually to 3.1.
