### ISSUE TITLE
Problems with PDB IDs containing whitespace

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#35]
If you request a PDB ID with trailing whitespace (e.g. http://eppic-web.org/ewui/#id/4Q4X%20%20), the extra whitespace gets trimmed off as expected and most of the page displays. However, the whitespace remains in the image URLs, leading to broken images.

Leading whitespace (e.g. http://eppic-web.org/ewui/#id/%204Q4X) breaks entirely, and the 'PDB ID not found' message is displayed. That's arguably a correct response, but it would be nice if the URLs accepted the same set of IDs that the search bar accepts.

**Comment by sbliven** [comment]
Perhaps it's worth mentioning that I have eppic set up as a search engine in Firefox/Chrome, which always bypasses the search bar and submits queries directly as URLs. If that's a common usecase, the #id parameter could be receiving arbitrary text, rather than just 4-letter uppercase IDs.

**Comment by josemduarte** [comment]
Fixed in 072b1994a531103b7813abfcedf561a50569183e
