### ISSUE TITLE
1zna: EPPIC 3.0-alpha does not stop with non-standard SGs and settings 

### ISSUE THREAD

**Issue by gcapitani** [eppic-team/eppic#37]
For entry 1zna (a Z-DNA tetramer) in non-standard SG B 2 21 2 EPPIC 3.0-alpha (unlike 2.1.2) does not issue the "non-standard space group error" and completes the run just calculating the AU interface. This version does not yet check for non-standard SGs and settings, which is needed to keep out several hundreds of affected entries in PDB-wide precomputations.

**Comment by sbliven** [comment]
This can be solved very similarly to #133

**Comment by josemduarte** [comment]
That's a good idea, I think we could simply add a new "nonStandard" flag to the PdbInfo table to be able to display this and #133 consistently. The flag would then be populated from BioJava. I can do that part.

**Comment by sbliven** [comment]
Ok, so we will implement this as follows:

1. [ ] Add `nonStandard` boolean column to PdbInfo. For testing purposes, this could be filled with random data or whatever
2. [ ] In the GUI, add a warning to the structure warnings list if this boolean is true. Warning should say "Non-standard space group. Only contacts in the asymmetric unit will be analyzed."
3. [ ] During database upload, the space group should be checked against the list of valid space groups. If it is not on the list, set `nonStandard=true`

**Comment by josemduarte** [comment]
So I'm working already in the server side of this. Pull request https://github.com/biojava/biojava/pull/604 is a step towards this. 

I think we should be able to capture 2 sub-cases here:
- non-standard spage groups, e.g. B 2 21 2 in 1zna
- non-standard coordinate frame convention, e.g. 4hhb and all those discussed in https://github.com/eppic-team/owl/issues/4. This is detectable by comparing the scale matrix in the file to our calculated scale matrix. 

I will add the `nonStandard` column to `PdbInfo` and set it to true in either of the 2 cases above. So I will take care of points 1 and 3 in @sbliven's list. Point 2 I will leave to @altheaparker. Only a small addition to the warning message: "Non-standard space group __or setting__. Only contacts in the asymmetric unit will be analyzed."

**Comment by josemduarte** [comment]
I've now done 1 and 3. 

I've actually added 2 fields in `PdbInfo` instead of just one:
- `nonStandardSg` : warning for this should be  "Non-standard space group. Only contacts in the asymmetric unit will be analyzed."
- `nonStandardCoordFrameConvention` : warning for this should be  "Non-standard coordinate frame convention. Only contacts in the asymmetric unit will be analyzed."

I've put the commit in branch `issue37`. It depends on this PR in biojava: https://github.com/biojava/biojava/pull/605 (which also needs to be cherry-picked into biojava's bugfixes-4.2)

**Comment by josemduarte** [comment]
I've now merged the branch with these changes. Note that it depends on biojava-4.2.5-SNAPSHOT (available from the bugfixes-4.2 branch).

**Comment by sbliven** [comment]
Is it possible to convert the dev db to have these columns, or do we need to wait for the next repopulation before testing this?

**Comment by josemduarte** [comment]
Running any of our scripts (with setting `hibernate.hbm2ddl.auto=update`, which is our default) against the database will update the schema, setting the fields to false. One can then set some to true with a manual update command. 

An alternative is doing a full run for 4hhb, produce the webui.dat file and then upload it with `UploadToDb` (with force replacement option).

**Comment by josemduarte** [comment]
I've just run the UploadToDb script in dev db, so the schema is updated.

**Comment by josemduarte** [comment]
Looks like this works now, thanks @altheaparker! Should we close?

**Comment by sbliven** [comment]
Looks good. The database needs to be repopulated, but manually setting values (3hbx and 1zna) shows that it works.
