### ISSUE TITLE
Interface clustering: rmsd vs contacts

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#41]
In structure 4p0t using 3.0-alpha, we get interfaces 1,6 clustered together. If one looks at them superposed they are similar but with a clear shift (a tilt or a small translation). 

For the purpose of looking at topology it is good that they are clustered. For other purposes it might not be. If one uses rmsd for clustering (eppic 2) then they are not clustered.

**Comment by josemduarte** [comment]
See also #40 and #39

**Comment by josemduarte** [comment]
For the record, the contact overlap score for interfaces 1,6 is 0.2368 (thus above threshold 0.2)

**Comment by josemduarte** [comment]
Perhaps the threshold should be simply a bit more strict.

For instance for the case 4adz, interfaces 4 and 10 are clustered together with a score of 0.25 (just 2 contacts in common out of 13+3/2=8). Looking at those 2 interfaces it is clear they are different, they should not be clustered together.

**Comment by josemduarte** [comment]
Another example is 4mbs. Interfaces 2 and 3 are clustered together, with a score 0.282. If one looks at the superposition they are somehow similar but not enormously.

It looks like a 0.3 cutoff should not be so bad and can avoid some false positives.

**Comment by sbliven** [comment]
Ok, lets just bump up the cutoff.

**Comment by josemduarte** [comment]
Bumped up the cutoff to 0.3
