### ISSUE TITLE
XML downloads will return error if a single PDB id is not in db

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#42]
e.g. 4qqi is not in the db, but 1smt and 1bxy are. The query:

```
http://www.eppic-web.org/ewui/ewui/dataDownload?type=xml&id=1smt,1bxy,4qqi
```

returns an HTTP error 412 with this message:

```
Input values are incorrect: Nothing found with the provided id:4qqi
```

What's the best solution for this? return all the valid values and ignore silently the invalid input?

**Comment by somody** [comment]
It might be easiest to just have the XML tags for that job hold nothing
<eppicAnalysis uid="???" jobId="4qqi" inputType="0"
inputName="4qqi"></eppicAnalysis>
or maybe even
<eppicAnalysis uid="???" jobId="4qqi" inputType="0"
inputName="4qqi">DNE</eppicAnalysis>

At least then they'll know when parsing that that one didn't work

**Comment by josemduarte** [comment]
From 3.1.0 only 1 id is allowed, this doesn't apply anymore.
