### ISSUE TITLE
Find a faster blast alternative

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#46]
[transferred from [JIRA](https://jira-bsse.ethz.ch/browse/CRK-138)]

Blast is very good but slow, especially for our kind of usage where we don't care about sensitivity so much (we look for >50% id homologs). 

Some alternatives are around:
- [SANS](http://www.ncbi.nlm.nih.gov/pubmed/22962464) and [SANSparallel](http://nar.oxfordjournals.org/content/early/2015/04/08/nar.gkv317.full) by Liisa Holm
- [USEARCH](http://drive5.com/usearch/) (commercial) 
- [BLAT](https://genome.ucsc.edu/FAQ/FAQblat.html#blat3) from UCSC. They also have a [commercial](http://www.kentinformatics.com/products.html) version of it

SANSparallel looks very promising, the [server](http://ekhidna2.biocenter.helsinki.fi/cgi-bin/sans/sans.cgi) is incredibly fast.

**Comment by josemduarte** [comment]
Another one that looks very promising is [LAMBDA](http://www.seqan.de/projects/lambda/). 

It even does blast tabular output (no XML though). I've tried it but couldn't make it work yet.

**Comment by josemduarte** [comment]
I managed in the end to run lambda. This is the command needed:

```
./bin/lambda -q query.fasta -d uniprot/uniprot_sprot.fasta -p blastp
```
The `-p blastp` is essential or otherwise `blastx` default is used and no hits found as the input is considered to be DNA.

I could index an old swissprot (15.9 just the swissprot part) and run against it as above without problems.

Now when I tried to index the latest full UniRef 100 I had a lot of issues.

This:
```
./bin/lambda_indexer -d uniref100.fasta -s db.seg
```
consumed all memory in my system (16GB) and was killed by the OS after a few minutes. 

From the docs `lambda_index --help`:
```
    -a, --algorithm STR
          Algorithm for SA construction (also used for FM; see Memory Requirements below!). One of mergesort,
          quicksortbuckets, quicksort, and skew7ext. Default: mergesort.

MEMORY REQUIREMENTS AND SPEED
    mergesort [RAM]: 14 * size(dbSeqs)

    mergesort [speed]: up to t threads

    quicksort and quicksortbuckets [RAM]: 7 * size(dbSeqs)

    quicksort [speed]: 1-2 threads

    quicksortbuckets [speed]: 1-2 threads for initial sort, up to t for buckets

    skew7ext [RAM]: 2 * size(dbSeqs)

    skew7ext [DISK]: 30 * size(dbSeqs)

    skew7ext [speed]: not parallelized

    size(dbSeqs) refers to the total sequence length and does not include IDs (which can account for >50% of the file
    size for protein databases). The space is the maximum obseverved factor, for many databases the factor is smaller.

    Use mergesort if you have enough memory! If not, you will probably want to use skew. For small databases and only
    a few cores the quicksorts might be a good tradeoff. mergesort and quicksortbuckets provide a rough progress
    estimate.

```

So it seems that it is impossible to run with the default algo because for current UniRef100 (26 GB full, perhaps ~20GB sequences only), it would need 14x20GB. So conclusion is that it can only be run with `-a skew7ext` in our 128GB machine. This was the command:
```
./bin/lambda_indexer -d $updir/uniref100.fasta -s $updir/db.seg -a skew7ext
```
It could go on for much longer, but then died later with a seg fault:
```
Start Wed May  6 22:57:16 CEST 2015

LAMBDA - Indexer
======================================================
Version 0.4.7

Loading Subject Sequences and Ids… done.
Dumping Subj Ids… done.
Constructing binary seqan masking from seg-file…Dumping binary seqan mask file… done.

Dumping unreduced Subj Sequences… done.
Generating Index…./index_it.sh: line 11: 21723 Segmentation fault      ./bin/lambda_indexer -d $updir/uniref100.fasta -s $updir/db.seg -a skew7ext

Exit state 139
End Thu May  7 00:30:22 CEST 2015

```

**Comment by josemduarte** [comment]
So the problems above are due to lack of disk space. After discussion in the mailing list, the developers say that in `-a skew7ext` mode, you need up to ~ x30 the sequence size in disk space. For our case it would be 30x20GB, so ~600GB. You still need quite some memory (~20GB perhaps). I couldn't run it in a 16GB RAM, 1.5TB disk server because of lack of memory. Whilst in the 128GB RAM server there's too little disk space. 

We are going to have to wait for the next version of the indexer...

**Comment by josemduarte** [comment]
Finally I could index UniRef_2012_06. I've then tried:
- A single sequence query: 1m40s
- A query file with 264 sequences: completed in 1m50s, i.e. ~0.5s per query!

So it looks that most of the time was spent in deserializing the index, the search is ultra fast

**Comment by gcapitani** [comment]
Very interesting! How did you avoid the segmentation fault of the indexer? Used > 16 GB RAM?

**Comment by josemduarte** [comment]
That was actually a pesimistic estimation of the performance. Now I did a larger test: a query of 3900 sequences (all pdb uniprot references starting with O):

```
$ time ./bin/lambda -q all_o_uniprots.fasta -d uniprot_2012_06/uniref100.fasta -p blastp
LAMBDA - the Local Aligner for Massive Biological DatA
======================================================
Version 0.4.7

Loading Subj Sequences… done.
Loading Subj Ids… done.
Reading Database Index from disk… done.
Loading Database Masking file… done.
Loading Query Sequences and Ids… done.
Searching and extending hits on-line...progress:
0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
|····*····*····*····*····*····*····*····*····*····|
Number of valid hits:                           1173751
Number of Queries with at least one valid hit:     3804

real	2m57.179s
user	40m10.940s
sys	0m20.919s

```

So the more realistic rate is 0.05s per query (multi-threaded in eppic01). That would give us the full pdb in under an hour.

@gcapitani this is an old(ish) uniref, that's why the indexing worked. Current uniprot would still be impossible at the moment.

**Comment by josemduarte** [comment]
The full pdb is actually 17min (on 32 threads):

```
time ./bin/lambda -q all_pdb.fasta -d uniprot_2012_06/uniref100.fasta -p blastp

LAMBDA - the Local Aligner for Massive Biological DatA
======================================================
Version 0.4.7

Loading Subj Sequences… done.
Loading Subj Ids… done.
Reading Database Index from disk… done.
Loading Database Masking file… done.
Loading Query Sequences and Ids… done.
Searching and extending hits on-line...progress:
0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
|····*····*····*····*····*····*····*····*····*····|
Number of valid hits:                           16700946
Number of Queries with at least one valid hit:     52682

real    17m4.891s
user    490m0.830s
sys     2m6.993s

```

**Comment by josemduarte** [comment]
From a sample of 5000 blast runs in 2015_05, this is the summary of the distribution of times-per-job (in seconds):
```
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  59.88  193.90  305.90  340.30  456.00 3395.00       1 
```
So the median is 5 minutes. This is running blast with single queries, multiquery would be faster.

**Comment by josemduarte** [comment]
Lambda 0.9.1 is out with amazing improvements, especially in the indexing. Below some preliminary tests with the pre-indexed UniRef100 they provide in [their website](https://github.com/seqan/lambda/wiki/Pre-built-Database-Indexes) (from September 2015).

With 260 query sequences, using 28 threads, memory usage is ~ 72GB :
```
LAMBDA - the Local Aligner for Massive Biological DatA
======================================================
Version 0.9.1

OPTIONS
 INPUT
  query file:               many_queries.fasta
  db file:                  uniref100_from_lambda/uniref100.fasta.gz
  db index type:            FM-Index
 OUTPUT (file)
  output file:              output.m8
  minimum % identity:       0
  maximum e-value:          0.1
  max #matches per query:   500
 OUTPUT (stdout)
  stdout is terminal:       0
  terminal width:           80
  verbosity:                2
 GENERAL
  double indexing:          0
  threads:                  28
  query partitions:         n/a
 TRANSLATION AND ALPHABETS
  genetic code:             n/a
  blast mode:               BLASTP
  original alphabet (query):aminoacid
  original alphabet (subj): aminoacid
  translated alphabet:      aminoacid
  reduced alphabet:         murphy10
 SEEDING
  seed length:              10
  seed offset:              10
  seed delta:               1
  seeds ungapped:           1
  seed gravity:             10
  min seed length:          10
 MISCELLANEOUS HEURISTICS
  pre-scoring:              on
  pre-scoring-region:       20
  pre-scoring-threshold:    2.000000
  putative-abundancy:       on
  putative-duplicates:      on
 SCORING
  scoring scheme:           62
  score-match:              n/a
  score-mismatch:           n/a
  score-gap:                -1
  score-gap-open:           -11
 EXTENSION
  x-drop:                   30
  band:                     2 * log(queryLength) + 1
 BUILD OPTIONS:
  cmake_build_type:         Release
  fastbuild:                off
  native_build:             off
  static_build:             on
  mmapped_db:               on

Loading Subj Sequences... done.
Runtime: 14.298s
Amount: 63391201

Loading Subj Ids... done.
Runtime: 0.00013241s

Loading Database Index... done.
Runtime: 46.5472s
No of Fibres: 23210822961

Loading Database Masking file... done.
Runtime: 29.0635s
Loading Query Sequences and Ids... done.
Runtime: 0.000562021s
Number of effective query sequences: 264
Longest query sequence: 740

Searching and extending hits on-line...progress:
0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
|....:....:....:....:....:....:....:....:....:....|
Runtime: 756.272s.

ESC[1m   HITS                                 RemainingESC[0m
   after Seeding                        58849367
 - masked                           0 = 58849367
 - merged                      698428 = 58150939
 - putative duplicates         869042 = 57281897
 - putative abundant         10087880 = 47194017
 - failed pre-extend test    45846198 =  1347819
 - failed %-identity test           0 =  1347819
 - failed e-value test        1027080 =   320739
 - abundant                    212501 =   108238
 - duplicates                       0ESC[1m =   108238ESC[0m

Number of valid hits:                           108238
Number of Queries with at least one valid hit:     260

real    14m11.001s
user    4m27.144s
sys     2m22.727s
```
It does ~ 3s per query

I haven't tried indexing yet, but it looks like now it could be feasible to index a current Uniref100 with our hardware.

**Comment by josemduarte** [comment]
Results for the full PDB in lambda 0.9.1 and Uniref100 from Sep 2015 as download from lambda website (28 threads):

```
LAMBDA - the Local Aligner for Massive Biological DatA
======================================================
Version 0.9.1

OPTIONS
 INPUT
  query file:               all_pdb.fasta
  db file:                  uniref100_from_lambda/uniref100.fasta.gz
  db index type:            FM-Index
 OUTPUT (file)
  output file:              output.m8
  minimum % identity:       0
  maximum e-value:          0.1
  max #matches per query:   500
 OUTPUT (stdout)
  stdout is terminal:       0
  terminal width:           80
  verbosity:                2
 GENERAL
  double indexing:          0
  threads:                  28
  query partitions:         n/a
 TRANSLATION AND ALPHABETS
  genetic code:             n/a
  blast mode:               BLASTP
  original alphabet (query):aminoacid
  original alphabet (subj): aminoacid
  translated alphabet:      aminoacid
  reduced alphabet:         murphy10
 SEEDING
  seed length:              10
  seed offset:              10
  seed delta:               1
  seeds ungapped:           1
  seed gravity:             10
  min seed length:          10
 MISCELLANEOUS HEURISTICS
  pre-scoring:              on
  pre-scoring-region:       20
  pre-scoring-threshold:    2.000000
  putative-abundancy:       on
  putative-duplicates:      on
 SCORING
  scoring scheme:           62
  score-match:              n/a
  score-mismatch:           n/a
  score-gap:                -1
  score-gap-open:           -11
 EXTENSION
  x-drop:                   30
  band:                     2 * log(queryLength) + 1
 BUILD OPTIONS:
  cmake_build_type:         Release
  fastbuild:                off
  native_build:             off
  static_build:             on
  mmapped_db:               on

Loading Subj Sequences... done.
Runtime: 0.558529s 
Amount: 63391201

Loading Subj Ids... done.
Runtime: 0.000143996s 

Loading Database Index... done.
Runtime: 15.4711s 
No of Fibres: 23210822961

Loading Database Masking file... done.
Runtime: 12.3686s 

Loading Query Sequences and Ids... done.
Runtime: 0.0835947s 
Number of effective query sequences: 54848
Longest query sequence: 5037

Searching and extending hits on-line...progress:
0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
|....:....:....:....:....:....:....:....:....:....|
Runtime: 2799.79s.

ESC[1m   HITS                                    RemainingESC[0m
   after Seeding                           13242897443
 - masked                              0 = 13242897443
 - merged                      178843167 = 13064054276
 - putative duplicates         150256250 = 12913798026
 - putative abundant          1482839793 = 11430958233
 - failed pre-extend test    11037219377 =   393738856
 - failed %-identity test              0 =   393738856
 - failed e-value test         337878260 =    55860596
 - abundant                     34764279 =    21096317
 - duplicates                          0ESC[1m =    21096317ESC[0m

Number of valid hits:                           21096317
Number of Queries with at least one valid hit:     52627

real    47m14.902s
user    1118m32.589s
sys     5m36.859s

```
The average per query is then much lower (0.05s).

**Comment by gcapitani** [comment]
Impressive! Re the indexing step, they say in the changelog that in 0.9.1 it needs 30% less RAM and it features up to 30% speedup.

**Comment by josemduarte** [comment]
Unfortunately the indexing of Uniref100_2015_10 is still not feasible on a 128GB RAM machine:
```
Start Son Okt 25 05:27:55 CET 2015
Loading Subject Sequences and Ids... done.
Runtime: 195.733s 
Number of sequences read: 66071141
Longest sequence read: 41965

Dumping Subj Ids... done.
Runtime: 276.625s 

Constructing binary seqan masking from seg-file...Exit state 247
End Son Okt 25 05:33:21 CET 2015
```

**Comment by josemduarte** [comment]
Another interesting application would be as a replacement of blastclust. An all-to-all run of lambda on all PDB chains takes 11 seconds...
```
LAMBDA - the Local Aligner for Massive Biological DatA
======================================================
Version 0.9.1

OPTIONS
 INPUT
  query file:               all_pdb.fasta
  db file:                  all_pdb/all_pdb.fasta
  db index type:            FM-Index
 OUTPUT (file)
  output file:              output.m8
  minimum % identity:       0
  maximum e-value:          0.1
  max #matches per query:   500
 OUTPUT (stdout)
  stdout is terminal:       1
  terminal width:           290
  verbosity:                2
 GENERAL
  double indexing:          0
  threads:                  28
  query partitions:         n/a
 TRANSLATION AND ALPHABETS
  genetic code:             n/a
  blast mode:               BLASTP
  original alphabet (query):aminoacid
  original alphabet (subj): aminoacid
  translated alphabet:      aminoacid
  reduced alphabet:         murphy10
 SEEDING
  seed length:              10
  seed offset:              10
  seed delta:               1
  seeds ungapped:           1
  seed gravity:             10
  min seed length:          10
 MISCELLANEOUS HEURISTICS
  pre-scoring:              on
  pre-scoring-region:       20
  pre-scoring-threshold:    2.000000
  putative-abundancy:       on
  putative-duplicates:      on
 SCORING
  scoring scheme:           62
  score-match:              n/a
  score-mismatch:           n/a
  score-gap:                -1
  score-gap-open:           -11
 EXTENSION
  x-drop:                   30
  band:                     2 * log(queryLength) + 1
 BUILD OPTIONS:
  cmake_build_type:         Release
  fastbuild:                off
  native_build:             off
  static_build:             on
  mmapped_db:               on

Loading Subj Sequences... done.
Runtime: 0.000585254s
Amount: 54848

Loading Subj Ids... done.
Runtime: 4.65577e-05s

Loading Database Index... done.
Runtime: 0.00701281s
No of Fibres: 12516557

Loading Database Masking file... done.
Runtime: 0.00236417s

Loading Query Sequences and Ids... done.
Runtime: 0.0868331s
Number of effective query sequences: 54848
Longest query sequence: 5037

Searching and extending hits on-line...progress:
0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
|....:....:....:....:....:....:....:....:....:....|
Runtime: 11.2235s.

   HITS                                 Remaining
   after Seeding                        12190595
 - masked                           0 = 12190595
 - merged                     3761690 =  8428905
 - putative duplicates        1017386 =  7411519
 - putative abundant                0 =  7411519
 - failed pre-extend test     6121292 =  1290227
 - failed %-identity test           0 =  1290227
 - failed e-value test         411242 =   878985
 - abundant                       200 =   878785
 - duplicates                       0 =   878785

Number of valid hits:                           878785
Number of Queries with at least one valid hit:   53452

real	0m11.368s
user	5m12.471s
sys	0m1.337s
```

**Comment by sbliven** [comment]
@josemduarte So If I read this right, all we have to do to make skew work is add 600GB of hard drive? Let's do it!

It does seem like your speed comparisons don't quite match our use cases. We want:

1. Total time to index uniref100 and query the whole pdb
2. Time to query a single sequence

The first will probably be dominated by the indexing time. If it takes a week using the slower skew heap then that's not too much improvement over BLAST. Do you have a feeling for how long indexing is likely to take from your runs with smaller databases? The second use case is probably dominated by reading in the index file, so I would still expect a few seconds for user jobs.

**Comment by josemduarte** [comment]
@sbliven well it's a long story (and a long thread, sorry for the spam). With the new lambda version (0.9.1) things are much better than they used to be in the first posts of this thread. They've introduced a new radix algo that has much lower RAM requirements. After talking to the developers they estimate we'd need 150GB to index a current UniRef100. I'm going to try that out if I can get hold of such a machine around here. You are right in any case that with the skew algo we could do it if we had a very large disk but also a lot of memory (~ 50GB or more). We couldn't do it with the available machines at PSI because we didn't have both of the requirements in one box.

About the 2 use-cases that you give above:

1. If we really can get the memory, the indexing runs in a few hours so that's not an issue and compares well to the time that blast requires to index (also a few hours). A possibility is also that someone somewhere provides monthly updated precomputed indices so that we all don't have to redo them. At the moment the lambda people provide the index of a ~ 2 months old Uniref, but they are not keeping it up to date (at least yet).
2. Time to query a single sequence is dominated indeed by reading the index file (a minute or more). __However__ they have now implemented (lambda 0.9.1) a shared memory approach (mmapped IO) that apparently is able to share the same index across different instances of the program. That comes close to a client-server architecture where the server is in the background holding the index in memory and the client sends queries that take very little time. Hopefully the full client-server thing comes with new versions.

**Comment by josemduarte** [comment]
I've come across another alternative recently: kclust/mmseqs from the Soeding group. See [paper](http://bioinformatics.oxfordjournals.org/content/early/2016/01/06/bioinformatics.btw006.full.pdf) and the github repo:

https://github.com/soedinglab/MMseqs

Actually the most up-to-date repo is:

https://github.com/soedinglab/MMseqs2

The nice thing is that they've implemented both sequence search and clustering. I haven't tried it yet so I have no idea how fast it is and how demanding in term of resources.

**Comment by lafita** [comment]
There is actually a version of mmseqs2 for searching highly similar sequences called Linclust (https://doi.org/10.1101/104034). They promise it runs in linear time, and it looks like the thing we need for EPPIC, but I have not tried it yet.

**Comment by lafita** [comment]
Additionally, the clustering with mmseqs2 can be updated, so that the computation after addition and removal of sequences takes less time, reusing the previous clustering calculation. This sounds really nice and applicable to our use. Here is the documentation on github, which explains well everything:

https://github.com/soedinglab/mmseqs2/wiki#linear-time-clustering-using-mmseqs-linclust
