### ISSUE TITLE
Predictions in peptide-protein interfaces are problematic

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#5]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Monday Jun 23, 2014 at 10:29 GMT_
_Originally opened as https://github.com/eppic-team/eppic-cli/issues/9_

---

[issue transferred from JIRA]

In a peptide-to-protein interface usually the prediction is alright for the protein side, but for the peptide side there are problems: 
- homologs are difficult to catch with blast (even when using PAM30 matrix as we do): many times we end up with 0 homologs
- in core-surface score: there's not enough free surface to have proper sampling (this commit https://github.com/eppic-team/eppic/commit/593f669e1893ffe375e090e0dc33f04e318b9aec  should have helped) 
- in core-rim: many times there's not even a rim: all residues are fully buried

Some examples: 
- 3bfq: this is FimG-FimF complex, good prediction based on the protein side only
- 1qsn: a case of 0 homologs for peptide side, even using PAM30 matrix
- 1f4v: quite good signal from peptide side but number of core residues fall below cutoff for nopred. The peptide-protein interface  is repeated 3 times in this structure (interface cluster 2, composed of interfaces 2,3,4) and for only 1 of the 3 there is a prediction
- 1w0w: a case of 0 homogs for peptide side, the protein side is not well predicted either because of separate issue with MHC sequences
- 1sdx: too few core residues in both sides
- 1w9q: the UniProt reference was not even found

A possible idea is to use some kind of geometric approach to detect these kind of interfaces, for instance the BSA/total ASA ratio should be quite high. What to do after to provide a meaningful evolutionary decision is not very clear anyway...

**Comment by sbliven** [comment]
Can we just accept these as weak predictions?

**Comment by josemduarte** [comment]
Realistically accepting them as weak predictions is about the best we can do for now. Let's see if we can do something in 3.1 or later.
