### ISSUE TITLE
Fix display of SG, resolution and Rfree for non-crystallographic entries

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#51]
Currently an NMR entry shows with SG P1, resolution 99 and some Rfree in web ui. This needs to be fixed.

**Comment by josemduarte** [comment]
Also crystallography entries with no Rfree or no resolution show with default values 99 and 1, e.g. 1var

**Comment by altheaparker** [comment]
When there is an experiment of type "NMR" the space group, r-free, and resolution could be all be set to "N/A" (to be discussed)

**Comment by josemduarte** [comment]
I'd say simply let's not display each of the fields if these conditions apply:
- Space Group: if experimental type is "NMR" don't display Space Group
- Resolution: if resolution >=99 don't display Resolution
- Rfree: if Rfree>=1 don't display Rfree

**Comment by altheaparker** [comment]
Is this a general rule that we can use for all cases (meaning entries that are not SOLUTION NMR but don't have space group, resolution, rfree)?

**Comment by josemduarte** [comment]
Yes this should be general for any entry.

**Comment by josemduarte** [comment]
Fixed in b46cdb47c3c0e122faf8d94832495b0b79d6967d, thanks @altheaparker !
