### ISSUE TITLE
MHC to peptide complexes: problems in core-surface scoring

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#6]
<a href="https://github.com/josemduarte"><img src="https://avatars.githubusercontent.com/u/6000474?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josemduarte](https://github.com/josemduarte)**
_Monday Jun 23, 2014 at 10:42 GMT_
_Originally opened as https://github.com/eppic-team/eppic-cli/issues/10_
---

In MHC-to-peptide complexes (e.g. 1w0w) the protein side gives usually a very high (xtal) score because the actual site that binds the peptide is the most variable in terms of sequence, this is an issue similar to antibodies. The difference is that for antibodies usually there's quite a mismatch from the PDB sequence to the found UniProt reference and then a nopred is produced because all the mismatches. For some reason in MHC case the found UniProt reference is usually matching very well and then the prediction procedes as usual. If one looks at the potato for one of these cases it's almost a negative of the usual situation: the binding site is warm colors and the rest of the surface is blue. 

E.g. for 1w0w one gets a core-surface score of 11.84

See also issue #9 which tends to happen together with this one as the partners of the MHC are always peptides

**Comment by sbliven** [comment]
Some false negatives are acceptable. I think we're doing the best we can.
