### ISSUE TITLE
CA-only structures produce pymol crashes (pymol 1.7.4)

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#62]
1rea is an example. It used to be fine with PyMOL 1.5 but 1.7 seems to crash for some reason (even eppic 2.1.2 crashes  when producing entropies.pse file)

**Comment by sbliven** [comment]
The crash comes when trying to ray-trace a view with no visible atoms. Primarily this happens when showing CA-only models as cartoons.

The crash only occurs in command line mode.

Example:
```pymol -c -d "load 1hzs.1.pdb.gz; as cartoon; ray; "```

**Comment by josemduarte** [comment]
So then it looks like some sort of bug in PyMOL, it shouldn't crash just because there's nothing visible. It must have been introduced some time after 1.5 (I'm pretty sure it was working back then). I've tried it now in 1.7.2 and I confirm I can reproduce it too.

**Comment by gcapitani** [comment]
The bug affects about 500 PDB entries out of 110'000. Those 500 now have been recalculated on our cluster with PyMOL 1.5 and uploaded to the db.

**Comment by sbliven** [comment]
Thomas Holder has already fixed this bug and will send us an updated version of PyMOL 1.7.6.

Of course, that will create PSE files in the new format, but I don't think we're doing anything so fancy that adding `set pse_export_version, 1.74` to our scripts won't work.

**Comment by sbliven** [comment]
I've verified that with the setting, the pse files are indeed backwards compatible. Thus we should add this line to all the pse scripts in the future and start using 1.7.6

Note that trying to set the variable in 1.7.4 or earlier results in a warning, so adding the line can't hurt.

**Comment by josemduarte** [comment]
I've added the TODO label so that we don't forget we need to patch the pymol scripts as described above.
