### ISSUE TITLE
Assembly detail links should show interface counts, or nothing if no interfaces belong to assembly

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#68]
I'm adding this issue here so that we can track it easier. It's almost done by now anyway... See commit 59bdc59e98ab0f0107832cd06581a0299f0f8e5f

**Comment by josemduarte** [comment]
The new feature shows really nicely in the dev server now, thanks @altheaparker ! However the links seem to be pointing now always to all interfaces instead of the corresponding subset of interfaces. This was working fine when we had the "Details" buttons.

**Comment by gcapitani** [comment]
Indeed the assembly-to-interface links seem to miss the final part indicating the subset: for instance in entry 1lcs, assembly 2, the link points to:

http://pc11467:8081/#interfaces/1lcs/    

(as all other links) instead of:

http://pc11467:8081/#interfaces/1lcs/2

**Comment by josemduarte** [comment]
Fixed in b46cdb47c3c0e122faf8d94832495b0b79d6967d
