### ISSUE TITLE
Extra column appears when navigating from interface clusters back to interfaces

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#70]
The new links in the general info box are really nice, thanks @altheaparker . However I've noticed a weird issue with an extra column appearing on the left of the main grid.

Steps to reproduce:
- load an entry, e.g. 3v1g
- click on "Interface Clusters" link in General Information panel
- click on "Interfaces" link in General Information panel: a new column with numbers appear in the main grid

**Comment by josemduarte** [comment]
Screenshot:

![screenshot from 2015-10-28 12-15-53](https://cloud.githubusercontent.com/assets/6000474/10800169/ad4c4198-7d6d-11e5-9eb8-0dc8882566b6.png)

**Comment by sbliven** [comment]
I can reproduce. The column seems to be the cluster ID. Oddly, it doesn't appear when unchecking the checkbox.

**Comment by gcapitani** [comment]
Same behavior as described by you guys in my case (both with Firefox on SL6 and Chrome on Win7).

**Comment by josemduarte** [comment]
Fixed in 38dae320d25fa07dd3cfbdfd36fa9ccf68023cd5
