### ISSUE TITLE
USE_ONLINE_PDB not honored

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#71]
The variable 'USE_ONLINE_PDB' is mentioned in eppic.conf and in an error message as causing eppic to auto-download files, but this doesn't seem to be implemented anywhere.

**Comment by josemduarte** [comment]
That's right, it's a left over from version 2. After the port to Biojava it wasn't re-implemented. See issue #56 explaining it.

**Comment by sbliven** [comment]
Ok, lets discuss there then.
