### ISSUE TITLE
Grids don't expand to full width on large screens

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#73]
We've been noticing this for a long time. In Mac OSX the grids are often displayed not covering the full width of the browser window. If one resizes the window for a while usually it's possible to get the grids properly displayed on the full width. 

Tested on Chrome/Firefox/Safari on Mac OSX 10.10.5 with 2560x1540 monitor. The problem seems to happen only when the width of the browser window is more than a certain size (around 2000 pixels), in smaller windows it does not seem to appear.

Perhaps the problem affects also other OSs with very large screens but we happened to notice only on Mac OSX. We need to check this on large screens on other OSs (2.5k wide or more). 

![screen shot 2015-11-13 at 2 41 04 pm](https://cloud.githubusercontent.com/assets/6000474/11159471/ac840026-8a14-11e5-9a02-e9b2a961c167.png)

![screen shot 2015-11-13 at 2 42 17 pm](https://cloud.githubusercontent.com/assets/6000474/11159484/d11057c8-8a14-11e5-8a49-18ece691dedb.png)

**Comment by sbliven** [comment]
We're having some difficulties reproducing this. I have a 2560x1600 screen with ubuntu. The width does seem to max out at 1876px, but that looks a lot wider than your screenshot.

@josemduarte, can you double-check that #66 doesn't effect Macs? Try both the fullscreen (green button) and the maximize (option-green button) starting with a small window and verify that the columns increase at least a bit.

**Comment by josemduarte** [comment]
To clarify I've seen this happening in Mac OSX only (all browsers), but not yet in Linux.

Certainly it is not the easiest thing to reproduce. What I do: before loading the eppic page I open a clean browser in almost full screen size (but not maximized). Then I open eppic main page and load a structure, for me it always shows like the screenshots above. The problem goes after some resizing.

**Comment by gcapitani** [comment]
I have tried to reproduce it on Mac OSX 10.10.5 with a 2880x1800 display, using Safari as described above: the problem does not appear.

**Comment by josemduarte** [comment]
Could you try firefox in that same machine?

**Comment by gcapitani** [comment]
No, it was not my machine and could just give it a quick try. So it needs to be tested thoroughly on that kind of display.

**Comment by sbliven** [comment]
I can reproduce on my linux machine, so @altheaparker should be able to work on this when she has time.

The weird thing is that minor resizing doesn't change anything. However, if you resize the window below ~2180px then all of a sudden it fills the width. This is also approximately the window width with the maximum table size (1876px), so there is something going on which drops resize events from particularly large windows.

**Comment by sbliven** [comment]
a467bf1 seems to fix the horizontal resizing, but I'm seeing some weird line spacing issues. Needs testing.

**Comment by gcapitani** [comment]
The weird line spacing issues appear in Chrome on Ubuntu, behavior seems OK in Firefox on Ubuntu.

**Comment by josemduarte** [comment]
Trying in Firefox on Ubuntu, the horizontal resizing seems to work better than before. However I still see resize problems after the grid is more than ~ 2000px wide (with total browser window width of ~ 2200px ). Once the grid reaches the 2000px it just doesn't expand anymore beyond that point. With widths below that value it behaves fine.

**Comment by gcapitani** [comment]
It appears now to work fine. The weird line spacing issues do not happen if the icons are present in the rows. So we close the issue at least for the moment.
