### ISSUE TITLE
Pymol bug for 3j20, 3j7a

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#8]
<a href="https://github.com/kumar-physics"><img src="https://avatars.githubusercontent.com/u/5636184?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kumar-physics](https://github.com/kumar-physics)**
_Monday Jul 21, 2014 at 08:49 GMT_
_Originally opened as https://github.com/eppic-team/eppic-cli/issues/12_
---

This bus was reported in our old JIRA.
"Pymol(version 1.5 and 1.4) hangs when one try to do surface plot of 3j20 chain W. Cut only chain W , put it in separate file and load it in pymol. Pymol hangs when you do surface plot of this file. 
Pymol version 1.2 on windows seems to work."

Now another PDB 3j7a also having the same bug for chain N. 

Further description of the bug:
Actually if you look at the output folder, the pse and pml files were produced for those problematic chains. When I try to load those pse files in a pymol session, I got the following error.
 **\* Error in `python2.7': free(): invalid next size (normal): 0x0000000002e092b0 ***
Aborted (core dumped)

Even though eppic-web shows an error message for those pdb entries, our pymol plugin could load all the interfaces correctly.  The problem comes only while plotting entropy mapping(potato).

**Comment by sbliven** [comment]
I'm going to assume this will work with pymol 1.8 or whatever we go with. If not it's a pymol bug.
