### ISSUE TITLE
Navigation does not work for user jobs

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#80]
When submitting user jobs, the navigation is broken, i.e. clicking on "View all interfaces" doesn't work. The problem is that the PDB id is null for user jobs and URLs are then written like `server/#interfaces/null/1`. The identifier that should go there is the job identifier (long alphanumerical string) and not the PDB id. 

See for instance http://pc11467.psi.ch:8081/#id/X0d7Q3aYJNme38oiEKB98LoCGdUTGk

**Comment by gcapitani** [comment]
The main navigation aspects now work, found two remaining sub-issues:
1) When accessing the Interface Analysis pages of individual assemblies from Assembly Analysis, the link appears to have the correct form `server/#interfaces/JobId/1`, but the resulting page is an All Interfaces one that shows indeed the full list of interfaces. By refreshing the page, it changes into something resembling the expected Interface Analysis page: the title changes to "Interface Analysis of: Assembly <n>", but with the wrong assembly number, the top Interface Analysis panels appear but do not display correctly and the main table still shows all interfaces.
2) Ticking the "Group similar interfaces" box still triggers the "Job with id Null" error.

**Comment by josemduarte** [comment]
It looks like this work well now, doesn't it? I'll close it but please reopen if anyone finds issues.

**Comment by gcapitani** [comment]
Thanks, it indeed seems to work fully OK now.
