### ISSUE TITLE
Remove guava dependency from sequencing module

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#83]
The sequencing module currently uses Google Guava for some utility functions. Should we rewrite these as vanilla java and remove the dependency? From a quick glance they look fairly easy to do without (only 4 classes; mostly stuff with an obvious, if less elegant, equivalent).

**Comment by josemduarte** [comment]
I think this issue should be in Biojava, shouldn't it?

**Comment by sbliven** [comment]
Oops, yes.

https://github.com/biojava/biojava/issues/375
