### ISSUE TITLE
Zoomed-in Assembly Diagram

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#85]
The assembly diagrams need to be presented at a more detailed level.

The assembly diagrams will be placed in the same directory as the 3D view images, and will be named as follows:

Thumbnail: 2gs2.diagram.1.75x75.png

```
params.getBaseName()+EppicParams.ASSEMBLIES_DIAGRAM_FILES_SUFFIX+"."+a.getId()+"."+DEF_TN_WIDTHS[0]+"x"+DEF_TN_HEIGHTS[0]+".png"
```

Full image: 2gs2.diagram.1.75x75.png

```
params.getBaseName()+EppicParams.ASSEMBLIES_DIAGRAM_FILES_SUFFIX+"."+a.getId()+"."+DEF_DIAGRAM_FULL_WIDTH+"x"+DEF_DIAGRAM_FULL_HEIGHT+".png"
```

(code as a guide only)

Initially I'm going to just symlink all of these images to a placeholder on dev, until the 'diagram' branch gets merged in and we re-run the precomputation.

The assembly diagrams should appear in the second column of the assembly (#id) page, as well as in the topology panel for the assembly itself.

**Comment by sbliven** [comment]
For future reference, symlinks were created with:

```bash
find . -iname '*.assembly.*.png'|
while read f; do
ln -s /data/webapps/files_2015_12/diagram_placeholder.800x800.png "$(echo "$f"|sed 's/\.assembly\./.diagram./;s/75x75/800x800/')";
ln -s /data/webapps/files_2015_12/diagram_placeholder.75x75.png "$(echo "$f"|sed 's/\.assembly\./.diagram./')";
done
```

**Comment by sbliven** [comment]
Ok, symlinks don't work and hard links are limited to 30k links per file, so I ended up copying the thumbnail placeholder all over.

**Comment by josemduarte** [comment]
Isn't the client side of this already implemented? Can we close it?

**Comment by sbliven** [comment]
Lets keep this open until the server-side part is in place, as a reminder to update the URLs in the client.
