### ISSUE TITLE
Broken link & tooltip for similar structures

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#86]
The similar structures icon (Icon 3 of 4 in the sequence panel next to each chain, with the circle branching out to three other circles) has the wrong link and tooltip. I just recently populated the database table that causes this icon to appear, exposing the bug.

The icon currently links to `/searchPdb/<JobId>/<repChain>`. This is missing the leading hash; it should be `/#searchPdb/<JobId>/<repChain>`.

Also, the tooltip should read "Search for PDB structures containing chains similar in sequence to this chain".

**Comment by gcapitani** [comment]
The icon is also slightly raised compared to the line of the other icons.

**Comment by sbliven** [comment]
I'm going to reopen this until the icon positioning problem is fixed.

(It's annoying that github automatically closes issues for you.)

**Comment by josemduarte** [comment]
Related to this, the "hand" mouse pointer is missing when hovering over the left 2 icons, whilst it is there for the 2 right icons. We should have the hand pointer always appear whenever there's an action button.

**Comment by gcapitani** [comment]
Everything appears now to work fine.
