### ISSUE TITLE
Remove comma-separated lists from the database

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#88]
I came up with another use case that's difficult with the current schema: Find the SeqCluster for a given PdbCode/(nonrepresentative)Chain. I'm currently doing this by joining to ChainCluster and using lots of like statements:

```
select * from ChainCluster where pdbCode="3lmn" and (
    memberChains = "B" or
    memberChains like 'B,%' or
    memberChains like '%,B,%' or
    memberChains like '%,B' );
```

There should really be an additional table for the members, rather than storing them in a comma-separated list.

**Comment by sbliven** [comment]
I just realized that the existing way to do this is `PdbInfo.getChainCluster()`, which essentially just loops over all clusters and calls split(',') from Java. I wonder whether we would see any noticeable performance gain by doing this in the database like above.

**Comment by josemduarte** [comment]
I agree that ideally there should be a table to map the chains. Having comma-separated list is a bad hack that we introduced to get around that problem in the wui. That is good enough for the wui where we don't care much about chains and only about chain clusters (entities). Of course if we want to query the db for something different, it'd be very useful to have chains explicitly.

**Comment by sbliven** [comment]
Ruthlessly closing as wontfix
