### ISSUE TITLE
Jmol broken

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#89]
Our version of Jmol's code-signing certificate seems to have expired in October. Running Jmol now gives an error, 'Certificate has been revoked, reason: CESSATION_OF_OPERATION'

It might be possible to fix this by updating Jmol (we're at 14.0.13 in production). We could also switch everyone to JavaScript with a quick patch to add `&version=js` to all the JmolViewer URLs.

Of course, the real solution is to use 3Dmol in eppic3, but I think we need a patch before then.

**Comment by josemduarte** [comment]
The patch to switch everyone to jsmol sounds like the best solution. Anyway it's already very difficult to run the java applet, I don't think many people would be affected.

**Comment by josemduarte** [comment]
Firefox will also drop support for java applets sometime before the end of this year

https://blog.mozilla.org/futurereleases/2015/10/08/npapi-plugins-in-firefox/

**Comment by josemduarte** [comment]
I was going to try fix this, but I'm too scared of breaking something else while doing it (the branch history after 2.1.2 is not so clean, long story). I think it'd be better to leave it as it is. It will be solved either by Firefox removing java support or us releasing 3.0. Let's hope we manage 3.0 first!
