### ISSUE TITLE
unusually large number of homologs for some  entries. 

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#9]
<a href="https://github.com/kumar-physics"><img src="https://avatars.githubusercontent.com/u/5636184?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kumar-physics](https://github.com/kumar-physics)**
_Tuesday Aug 05, 2014 at 10:42 GMT_
_Originally opened as https://github.com/eppic-team/eppic-cli/issues/13_

---

The expected maximum number of homologs after redundancy reduction would be around 100 . But in some cases it goes more than 2000.

This is the MySQL query to get the list
select chainCluster_uid,count(_) from Homolog group by chainCluster_uid having count(_)>200;

There are about 612 entries having more than 200 homologs.

**Comment by sbliven** [comment]
Could relate to #5.

How important is this issue? Can we put it off until 3.1?

**Comment by josemduarte** [comment]
Not highest priority. Let's move it to 3.1
