### ISSUE TITLE
Non-contacts in Contacts database

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#90]
I noticed that there are some entries in the Contacts table where at least one of the residues is not actually buried. For instance, in 1faa residue 46 is fully buried, yet it appears in a contact with residue 6. A few other residues are annotated as surface, but appear in contacts

```
SELECT i.pdbCode, i.interfaceId, c.firstResNumber,rb.side, rb.region, rb.asa, rb.bsa, c.uid
FROM Interface AS i
JOIN ResidueBurial AS rb ON i.uid = rb.interfaceItem_uid
JOIN ResidueInfo AS ri ON ri.uid = rb.residueInfo_uid
JOIN Contact AS c ON i.uid = c.interfaceItem_uid
WHERE i.pdbCode="1faa"
AND rb.region < 0
AND (c.firstResNumber = ri.residueNumber AND NOT rb.side )
;
+---------+-------------+----------------+------+--------+------------------+------------------+
| pdbCode | interfaceId | firstResNumber | side | region | asa              | bsa              |
+---------+-------------+----------------+------+--------+------------------+------------------+
| 1faa    |           1 |             49 |      |     -1 | 4.93294344543241 | 4.93294344543241 |
| 1faa    |           1 |             52 |      |      0 | 9.44757126266872 |                0 |
| 1faa    |           1 |            114 |      |      0 | 89.7009559111854 |                0 |
+---------+-------------+----------------+------+--------+------------------+------------------+
3 rows in set (0.19 sec)
```

Are these expected? If so, we should check to make sure we aren't assuming that all contacts are actually participating in the interface (as I assumed).

BTW, finding such cases would be much easier if we had a foreign key between Contact and ResidueInfo, as suggested in #87

**Comment by josemduarte** [comment]
I think the issue is the 2 different ways to look at contacts which are completely independent:

1. Based on a fixed distance cutoff on all atoms

2. Based on buried surface area calculated through rolling ball algorithm

What we have in contacts table is calculated through 1: a pair in contacts means that there is at least a pair of atoms from each side of the 2 residues that is within the distance cutoff (I think it is 6 A). On top of that we also add to the contacts table the BSA, ASA values that we obtained independently with procedure 2.

**Comment by sbliven** [comment]
Ah, that makes sense. On the website we seem to be using the BSA definition though. Is there anywhere besides this table that's based on distance?

Is it possible for residues to pass our burial cutoff (I think 5Å^2) without having atoms within the distance cutoff?

**Comment by josemduarte** [comment]
> Is there anywhere besides this table that's based on distance?

Not that I remember now. 

The detection of interfaces _is_ based on distance cutoff, only after we detect an interface through distance then we calculate BSA. 

> Is it possible for residues to pass our burial cutoff (I think 5Å^2) without having atoms within the distance cutoff?

Good question! I don't really know. I guess you could fabricate an edge-case where that could happen. But it is unlikely. The water probe that we use is 1.4 A in radius. Which means 2 balls will touch when 4x1.4 A = 5.6 A apart.
