### ISSUE TITLE
Resolution value without unit 

### ISSUE THREAD

**Issue by gcapitani** [eppic-team/eppic#92]
In the "experimental details" line of the assembly analysis page, the resolution value has no unit
(it should be angstrom).

**Comment by gcapitani** [comment]
The same applies to the ASA and BSA columns in the Details table

**Comment by josemduarte** [comment]
There are units as far as I can see. 

Do you mean this one?
<img width="576" alt="screen shot 2016-02-22 at 8 49 14 am" src="https://cloud.githubusercontent.com/assets/6000474/13225337/3fcb1e02-d941-11e5-9259-7cebe44f58e1.png">

And in details table there are units on column headers, if this is the details table that you mean:
<img width="492" alt="screen shot 2016-02-22 at 8 51 14 am" src="https://cloud.githubusercontent.com/assets/6000474/13225376/799248ea-d941-11e5-8034-a8c075bca9d7.png">

**Comment by gcapitani** [comment]
Yes, the units for resolution in the "experimental details" line and in the ASA and BSA column titles in the Details table have just been added, so we can close the issue.

**Comment by josemduarte** [comment]
Ah! sorry I didn't notice that!

**Comment by gcapitani** [comment]
Actually the bottom image in your comment made me notice a very small inconsistency: in the top left corner of the details table we have Angstrom denoted with A and in the other instances with the proper symbol. So thanks!

**Comment by gcapitani** [comment]
As noted above, Angstrom in the top left corner of the details table should also be denoted with the proper symbol

**Comment by gcapitani** [comment]
Also, in the Similar structures table, the column titles for unit cell parameters and resolution lack the units.

**Comment by gcapitani** [comment]
All OK now
