### ISSUE TITLE
High Rfree warning / low resolution warning don't refresh properly

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#93]
E.g. 1fkd.

This must be related with the default value of Rfree, most likely it's 0 and the condition <0.3 then shows the warning. We should have no Rfree warning if we the entry has no Rfree annotated.

**Comment by sbliven** [comment]
Jose, I am unable to reproduce this, either on the dev server or in production. Can you double-check the PDB ID?

There is one entry with Rfree=0 in the dev database (3v49). However, it does not seem to be displayed in the general info pane (as expected). I've also tried a bunch with Rfree=1 (e.g. 1a6u), and they likewise don't show either Rfree or a warning.

**Comment by josemduarte** [comment]
Yes you are right, can't reproduce it myself either!

So looking into it again it looks like a problem of refreshing the warning after you load an entry with high r-free. I'll change the title of the issue to reflect that's the real bug.

Steps to reproduce:
- load 4xt3 (an entry with actual high Rfree): the warning appears correctly
- load 1smt (low Rfree): the warning stays there incorrectly

This also happens for the low resolution warning, e.g.:
- load 4xam (an entry with actual low resolution): the low resolution warning appears correctly
- load 3hbx (normal resolution): the low resolution warning stays there incorrectly

**Comment by gcapitani** [comment]
Works fine now
