### ISSUE TITLE
Problems with 3D viewer selector

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#95]
The 3D viewer selector (combo-box selecting between `PDB` and `3Dmol.js`) is not working properly. A few issues:

- when switching from _assemblies_ view to _interfaces_ view or the other way around, the selector doesn't keep the setting. E.g. if in `PDB` setting when in _assemblies_ view, then it should stay on `PDB` setting when in _interfaces_ view. 
- in _interfaces_ view, the `PDB` setting (which should download a file after clicking) does not work properly, nothing happens after clicking. I suspect the link that it points too is not correctly constructed, it should be like:
```
http://pc11467.psi.ch:8081/ewui/fileDownload?type=interface&id=1smt&interfaceId=1&type=interface&coordsFormat=cif
```

**Comment by gcapitani** [comment]
Also, the combo-box option 3Dmol.js should be renamed ngl

**Comment by gcapitani** [comment]
Works OK now.

**Comment by josemduarte** [comment]
The switching of the selector works great now, thanks @altheaparker .

However the second issue mentioned above (`PDB` setting in interfaces view not downloading a file) is still occurring. That one should be easy to fix, it must be only a matter of pointing to the right URL as mentioned above.

**Comment by gcapitani** [comment]
Good catch, thanks @josemduarte

**Comment by gcapitani** [comment]
The PDB setting in interfaces view now works, _i.e._ clicking leads to interface download (.cif file).
