### ISSUE TITLE
Use symmetry font instead of our own symmetry icons?

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#97]
I've just come across this:

http://www.iucr.org/resources/symmetry-font

A really cool font created by Ulrich Mueller that contains all the icons that we re-created ourselves for the server. Perhaps we could just switch to that, instead of using our own icons. With HTML5 it should be possible to use the ttf font directly. 

Low priority in any case.

**Comment by sbliven** [comment]
Cool idea, but probably not worth pursuing right now. We'd have to use icons as a fallback for HTML4 in any case.
