### ISSUE TITLE
Interfaces view shows "assembly 0" on header when loaded from URL

### ISSUE THREAD

**Issue by josemduarte** [eppic-team/eppic#99]
If I paste an _interfaces_ view URL in the browser, e.g. `http://pc11467.psi.ch:8081/#interfaces/4hnw`, the full list of interfaces does appear in the list, but the other panels above appear as if trying to display an "Assembly 0". See screenshot:

![screenshot from 2016-03-30 10-05-33](https://cloud.githubusercontent.com/assets/6000474/14150666/f7f5b73c-f65e-11e5-9b21-e48b3d4ac893.png)

In normal navigation from one panel to another, this doesn't occur. It only happens when pasting the URL or refreshing the browser on that URL.

**Comment by gcapitani** [comment]
Works fine now.
